/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectgui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author x14472008
 */
public class AlgebraLC extends javax.swing.JFrame {

    /**
     * Creates new form statsAndFun
     */
    public AlgebraLC() {
        initComponents();
        HighlvlStats.setVisible(false);
        OrdinarylvlStats.setVisible(false);
        ButtonGroup bg1 = new ButtonGroup();
            bg1.add(answer1w);
            bg1.add(answer2w);
            bg1.add(answer3c);
        ButtonGroup bg2 = new ButtonGroup();
            bg2.add(answer1w1);
            bg2.add(answer2w1);
            bg2.add(answer3c1);
        ButtonGroup bg3 = new ButtonGroup();
            bg3.add(answer1w3);
            bg3.add(answer2w3);
            bg3.add(answer3c3);
        ButtonGroup bg4 = new ButtonGroup();
            bg3.add(answer1w4);
            bg3.add(answer2w4);
            bg3.add(answer3c4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StatsPnlJC = new javax.swing.JPanel();
        headLbl = new javax.swing.JLabel();
        headLbl2 = new javax.swing.JLabel();
        highBtn = new javax.swing.JButton();
        ordBtn = new javax.swing.JButton();
        DevBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        ordHomeMain = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        OrdinarylvlStats = new javax.swing.JPanel();
        ordHead = new javax.swing.JLabel();
        DevBtn3 = new javax.swing.JButton();
        ordHomeMain3 = new javax.swing.JButton();
        calc5 = new javax.swing.JButton();
        backBtn4 = new javax.swing.JButton();
        question4 = new javax.swing.JButton();
        question5 = new javax.swing.JButton();
        Question4 = new javax.swing.JPanel();
        jTextArea5 = new javax.swing.JTextArea();
        answer3c3 = new javax.swing.JRadioButton();
        answer1w3 = new javax.swing.JRadioButton();
        answer2w3 = new javax.swing.JRadioButton();
        SubmitBtn3 = new javax.swing.JButton();
        Question5 = new javax.swing.JPanel();
        jTextArea6 = new javax.swing.JTextArea();
        answer3c4 = new javax.swing.JRadioButton();
        answer1w4 = new javax.swing.JRadioButton();
        answer2w4 = new javax.swing.JRadioButton();
        SubmitBtn4 = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        HighlvlStats = new javax.swing.JPanel();
        highHead = new javax.swing.JLabel();
        DevBtn2 = new javax.swing.JButton();
        ordHomeMain2 = new javax.swing.JButton();
        calc4 = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        question1 = new javax.swing.JButton();
        question2 = new javax.swing.JButton();
        Question1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        answer3c = new javax.swing.JRadioButton();
        answer1w = new javax.swing.JRadioButton();
        answer2w = new javax.swing.JRadioButton();
        SubmitBtn = new javax.swing.JButton();
        Question2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        answer3c1 = new javax.swing.JRadioButton();
        answer1w1 = new javax.swing.JRadioButton();
        answer2w1 = new javax.swing.JRadioButton();
        SubmitBtn1 = new javax.swing.JButton();
        background1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setMaximumSize(new java.awt.Dimension(400, 480));
        setMinimumSize(new java.awt.Dimension(400, 480));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        StatsPnlJC.setLayout(null);

        headLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headLbl.setForeground(new java.awt.Color(240, 240, 240));
        headLbl.setText("Algebra");
        StatsPnlJC.add(headLbl);
        headLbl.setBounds(160, 20, 110, 50);

        headLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headLbl2.setForeground(new java.awt.Color(255, 255, 255));
        headLbl2.setText("Leaving Cert");
        StatsPnlJC.add(headLbl2);
        headLbl2.setBounds(160, 80, 110, 30);

        highBtn.setText("Higher Level");
        highBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(highBtn);
        highBtn.setBounds(120, 130, 160, 70);

        ordBtn.setText("Ordinary Level");
        ordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(ordBtn);
        ordBtn.setBounds(120, 240, 160, 70);

        DevBtn.setText("Developer");
        DevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(DevBtn);
        DevBtn.setBounds(150, 370, 110, 29);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(backBtn);
        backBtn.setBounds(20, 420, 110, 40);

        ordHomeMain.setText("Home");
        ordHomeMain.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMainActionPerformed(evt);
            }
        });
        StatsPnlJC.add(ordHomeMain);
        ordHomeMain.setBounds(150, 420, 110, 40);

        calc.setText("Calculator");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        StatsPnlJC.add(calc);
        calc.setBounds(280, 420, 110, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        StatsPnlJC.add(background);
        background.setBounds(0, 0, 400, 480);

        getContentPane().add(StatsPnlJC);
        StatsPnlJC.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.setLayout(null);

        ordHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead.setForeground(new java.awt.Color(255, 255, 255));
        ordHead.setText("Ordinary Level");
        OrdinarylvlStats.add(ordHead);
        ordHead.setBounds(110, 40, 200, 30);

        DevBtn3.setText("Developer");
        DevBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtn3ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(DevBtn3);
        DevBtn3.setBounds(150, 370, 110, 29);

        ordHomeMain3.setText("Home");
        ordHomeMain3.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMain3ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(ordHomeMain3);
        ordHomeMain3.setBounds(150, 420, 110, 40);

        calc5.setText("Calculator");
        calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc5ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(calc5);
        calc5.setBounds(280, 420, 110, 40);

        backBtn4.setText("Back");
        backBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn4ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(backBtn4);
        backBtn4.setBounds(20, 420, 110, 40);

        question4.setText("Question1");
        question4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question4ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(question4);
        question4.setBounds(80, 70, 97, 29);

        question5.setText("Question2");
        question5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question5ActionPerformed(evt);
            }
        });
        OrdinarylvlStats.add(question5);
        question5.setBounds(160, 70, 97, 29);

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jTextArea5.setText("\n\n          Solve for x : 2(4 − 3x) + 12 = 7x – 5(2x − 7).          ");
        Question4.add(jTextArea5);

        answer3c3.setText("x = 3");
        answer3c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3c3ActionPerformed(evt);
            }
        });
        Question4.add(answer3c3);

        answer1w3.setText("x = 5");
        Question4.add(answer1w3);

        answer2w3.setText("x = -5");
        answer2w3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2w3ActionPerformed(evt);
            }
        });
        Question4.add(answer2w3);

        SubmitBtn3.setText("Submit");
        SubmitBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn3ActionPerformed(evt);
            }
        });
        Question4.add(SubmitBtn3);

        OrdinarylvlStats.add(Question4);
        Question4.setBounds(10, 90, 380, 120);

        jTextArea6.setColumns(20);
        jTextArea6.setRows(5);
        jTextArea6.setText("\n                                   Verify x = -5\n                     2(4 - 3x) + 12 = 7x – 5(2x - 7).                   ");
        Question5.add(jTextArea6);

        answer3c4.setText("-5");
        Question5.add(answer3c4);

        answer1w4.setText("50");
        answer1w4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1w4ActionPerformed(evt);
            }
        });
        Question5.add(answer1w4);

        answer2w4.setText("70");
        answer2w4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2w4ActionPerformed(evt);
            }
        });
        Question5.add(answer2w4);

        SubmitBtn4.setText("Submit");
        SubmitBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn4ActionPerformed(evt);
            }
        });
        Question5.add(SubmitBtn4);

        OrdinarylvlStats.add(Question5);
        Question5.setBounds(10, 90, 380, 130);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        OrdinarylvlStats.add(background2);
        background2.setBounds(0, 0, 400, 480);

        getContentPane().add(OrdinarylvlStats);
        OrdinarylvlStats.setBounds(0, 0, 400, 480);

        HighlvlStats.setLayout(null);

        highHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        highHead.setForeground(new java.awt.Color(255, 255, 255));
        highHead.setText("Higher Level");
        HighlvlStats.add(highHead);
        highHead.setBounds(130, 40, 200, 40);

        DevBtn2.setText("Developer");
        DevBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtn2ActionPerformed(evt);
            }
        });
        HighlvlStats.add(DevBtn2);
        DevBtn2.setBounds(150, 370, 110, 29);

        ordHomeMain2.setText("Home");
        ordHomeMain2.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMain2ActionPerformed(evt);
            }
        });
        HighlvlStats.add(ordHomeMain2);
        ordHomeMain2.setBounds(150, 420, 110, 40);

        calc4.setText("Calculator");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });
        HighlvlStats.add(calc4);
        calc4.setBounds(280, 420, 110, 40);

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        HighlvlStats.add(backBtn2);
        backBtn2.setBounds(20, 420, 110, 40);

        question1.setText("Question1");
        question1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question1ActionPerformed(evt);
            }
        });
        HighlvlStats.add(question1);
        question1.setBounds(80, 70, 97, 29);

        question2.setText("Question2");
        question2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                question2ActionPerformed(evt);
            }
        });
        HighlvlStats.add(question2);
        question2.setBounds(160, 70, 97, 29);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/LC-HLQ1.png"))); // NOI18N
        Question1.add(jLabel1);

        answer3c.setText("4x - 3");
        answer3c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3cActionPerformed(evt);
            }
        });
        Question1.add(answer3c);

        answer1w.setText("x - 6");
        answer1w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1wActionPerformed(evt);
            }
        });
        Question1.add(answer1w);

        answer2w.setText("2x - 3");
        answer2w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2wActionPerformed(evt);
            }
        });
        Question1.add(answer2w);

        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        Question1.add(SubmitBtn);

        HighlvlStats.add(Question1);
        Question1.setBounds(10, 90, 380, 280);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/LC-HLQ2.png"))); // NOI18N
        Question2.add(jLabel2);

        answer3c1.setText("x = -5");
        answer3c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3c1ActionPerformed(evt);
            }
        });
        Question2.add(answer3c1);

        answer1w1.setText("x = 10");
        Question2.add(answer1w1);

        answer2w1.setText("x = 6");
        answer2w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2w1ActionPerformed(evt);
            }
        });
        Question2.add(answer2w1);

        SubmitBtn1.setText("Submit");
        SubmitBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtn1ActionPerformed(evt);
            }
        });
        Question2.add(SubmitBtn1);

        HighlvlStats.add(Question2);
        Question2.setBounds(10, 90, 380, 280);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        HighlvlStats.add(background1);
        background1.setBounds(0, 0, 400, 480);

        getContentPane().add(HighlvlStats);
        HighlvlStats.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordBtnActionPerformed
        StatsPnlJC.setVisible(false);
       OrdinarylvlStats.setVisible(true);
    }//GEN-LAST:event_ordBtnActionPerformed

    private void highBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highBtnActionPerformed
       StatsPnlJC.setVisible(false);
       HighlvlStats.setVisible(true);
    }//GEN-LAST:event_highBtnActionPerformed

    private void DevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtnActionPerformed
        this.setVisible(false);
        new QuestionGUI().setVisible(true);

    }//GEN-LAST:event_DevBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void ordHomeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMainActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMainActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_calcActionPerformed

    private void DevBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtn2ActionPerformed
        this.setVisible(false);
        new QuestionGUI().setVisible(true);

    }//GEN-LAST:event_DevBtn2ActionPerformed

    private void ordHomeMain2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMain2ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMain2ActionPerformed

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_calc4ActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
                       
       boolean answer = false;
        if(answer1w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer2w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, " sorry that is an incorrect answer, please try again.");            
        }
        else if (answer3c.isSelected()){
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer");
        }
        else{
            answer = false;
            JOptionPane.showMessageDialog(null, "error, please try again");
        }
        if (answer == true){
            Question1.setVisible(false);
            Question2.setVisible(true);
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        HighlvlStats.setVisible(false);
        StatsPnlJC.setVisible(true);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void answer2wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2wActionPerformed

    private void question1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question1ActionPerformed
        Question2.setVisible(false);
        Question1.setVisible(true);
    }//GEN-LAST:event_question1ActionPerformed

    private void question2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question2ActionPerformed
        Question2.setVisible(true);
        Question1.setVisible(false);
    }//GEN-LAST:event_question2ActionPerformed

    private void answer2w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2w1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2w1ActionPerformed

    private void SubmitBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn1ActionPerformed
        boolean answer = false;
        if(answer1w1.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer2w1.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else if (answer3c1.isSelected()){
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        else{
            answer = false;
            JOptionPane.showMessageDialog(null, "error, please try again");
        }
        if (answer == true){
            Question1.setVisible(false);
            Question2.setVisible(false);
        }
    }//GEN-LAST:event_SubmitBtn1ActionPerformed

    private void answer3cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3cActionPerformed

    private void DevBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DevBtn3ActionPerformed

    private void ordHomeMain3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMain3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHomeMain3ActionPerformed

    private void calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc5ActionPerformed

    private void backBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn4ActionPerformed
        OrdinarylvlStats.setVisible(false);
        StatsPnlJC.setVisible(true);
    }//GEN-LAST:event_backBtn4ActionPerformed

    private void question4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question4ActionPerformed
        Question5.setVisible(false);
        Question4.setVisible(true);
    }//GEN-LAST:event_question4ActionPerformed

    private void question5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_question5ActionPerformed
        Question5.setVisible(true);
        Question4.setVisible(false);
    }//GEN-LAST:event_question5ActionPerformed

    private void answer3c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3c3ActionPerformed

    private void answer2w3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2w3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2w3ActionPerformed

    private void SubmitBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn3ActionPerformed
         boolean answer = false;
        if(answer1w3.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer2w3.isSelected()){
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");            
        }
        else if (answer3c3.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = false;
            JOptionPane.showMessageDialog(null, "error, please try again");
        }
        if (answer == true){
            Question4.setVisible(false);
            Question5.setVisible(true);
        }
    }//GEN-LAST:event_SubmitBtn3ActionPerformed

    private void answer2w4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2w4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2w4ActionPerformed

    private void SubmitBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtn4ActionPerformed
        boolean answer = false;
        if(answer1w4.isSelected()){
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer");
        }
        else if (answer2w4.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, " sorry that is an incorrect answer, please try again.");            
        }
        else if (answer3c4.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = false;
            JOptionPane.showMessageDialog(null, "error, please try again");
        }
        if (answer == true){
            Question4.setVisible(false);
            Question5.setVisible(false);
        }
    }//GEN-LAST:event_SubmitBtn4ActionPerformed

    private void answer1w4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1w4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1w4ActionPerformed

    private void answer1wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1wActionPerformed

    private void answer3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlgebraLC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DevBtn;
    private javax.swing.JButton DevBtn2;
    private javax.swing.JButton DevBtn3;
    private javax.swing.JPanel HighlvlStats;
    private javax.swing.JPanel OrdinarylvlStats;
    private javax.swing.JPanel Question1;
    private javax.swing.JPanel Question2;
    private javax.swing.JPanel Question4;
    private javax.swing.JPanel Question5;
    private javax.swing.JPanel StatsPnlJC;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JButton SubmitBtn1;
    private javax.swing.JButton SubmitBtn3;
    private javax.swing.JButton SubmitBtn4;
    private javax.swing.JRadioButton answer1w;
    private javax.swing.JRadioButton answer1w1;
    private javax.swing.JRadioButton answer1w3;
    private javax.swing.JRadioButton answer1w4;
    private javax.swing.JRadioButton answer2w;
    private javax.swing.JRadioButton answer2w1;
    private javax.swing.JRadioButton answer2w3;
    private javax.swing.JRadioButton answer2w4;
    private javax.swing.JRadioButton answer3c;
    private javax.swing.JRadioButton answer3c1;
    private javax.swing.JRadioButton answer3c3;
    private javax.swing.JRadioButton answer3c4;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn4;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JButton calc;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc5;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel headLbl2;
    private javax.swing.JButton highBtn;
    private javax.swing.JLabel highHead;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton ordBtn;
    private javax.swing.JLabel ordHead;
    private javax.swing.JButton ordHomeMain;
    private javax.swing.JButton ordHomeMain2;
    private javax.swing.JButton ordHomeMain3;
    private javax.swing.JButton question1;
    private javax.swing.JButton question2;
    private javax.swing.JButton question4;
    private javax.swing.JButton question5;
    // End of variables declaration//GEN-END:variables
}
