/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgui;

/**
 *
 * @author dylankilkenny
 */
public class ExamPapers extends javax.swing.JFrame {

    /**
     * Creates new form ExamPapers
     */
    public ExamPapers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExamPapers = new javax.swing.JPanel();
        backOrd = new javax.swing.JButton();
        ordHead = new javax.swing.JLabel();
        calc1 = new javax.swing.JButton();
        ordHome = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(200, 100, 400, 500));
        setMaximumSize(new java.awt.Dimension(400, 500));
        setMinimumSize(new java.awt.Dimension(400, 500));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        ExamPapers.setLayout(null);

        backOrd.setText("Back");
        backOrd.setMaximumSize(new java.awt.Dimension(110, 40));
        backOrd.setMinimumSize(new java.awt.Dimension(110, 40));
        backOrd.setPreferredSize(new java.awt.Dimension(110, 40));
        backOrd.setSize(new java.awt.Dimension(110, 40));
        backOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backOrdActionPerformed(evt);
            }
        });
        ExamPapers.add(backOrd);
        backOrd.setBounds(10, 420, 110, 40);

        ordHead.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        ordHead.setForeground(new java.awt.Color(255, 255, 255));
        ordHead.setText("Coming Soon...");
        ExamPapers.add(ordHead);
        ordHead.setBounds(70, 100, 300, 70);

        calc1.setText("Calculator");
        calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc1ActionPerformed(evt);
            }
        });
        ExamPapers.add(calc1);
        calc1.setBounds(280, 420, 110, 40);

        ordHome.setText("Home");
        ordHome.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome.setSize(new java.awt.Dimension(110, 40));
        ordHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeActionPerformed(evt);
            }
        });
        ExamPapers.add(ordHome);
        ordHome.setBounds(140, 420, 110, 40);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        ExamPapers.add(background2);
        background2.setBounds(0, 0, 400, 480);

        getContentPane().add(ExamPapers);
        ExamPapers.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backOrdActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backOrdActionPerformed

    private void calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc1ActionPerformed

    private void ordHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamPapers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamPapers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ExamPapers;
    private javax.swing.JButton backOrd;
    private javax.swing.JLabel background2;
    private javax.swing.JButton calc1;
    private javax.swing.JLabel ordHead;
    private javax.swing.JButton ordHome;
    // End of variables declaration//GEN-END:variables
}
