/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgui;

/**
 *
 * @author x14472008
 */
public class MainMenu extends javax.swing.JFrame {
    

    /**
     * Creates new form ProjectJFrame
     */
    public MainMenu() {
        setSize(600,600);
    setLocation(100,100);
        
        
        initComponents();
        jcBtnAlg.setVisible(false);
        lcBtnAlg.setVisible(false);
        jcBtnExam.setVisible(false);
        lcBtnExam.setVisible(false);
        jcBtnStat.setVisible(false);
        lcBtnStat.setVisible(false);
        jcBtnNum.setVisible(false);
        lcBtnNum.setVisible(false);
        jcBtnFun.setVisible(false);
        lcBtnFun.setVisible(false);
        AlgLbl.setVisible(false); 
        FunLbl.setVisible(false); 
        NumLbl.setVisible(false); 
        StatLbl.setVisible(false); 
        StatLbl1.setVisible(false); 
        ExamLbl.setVisible(false); 
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPnl = new javax.swing.JPanel();
        AlgebraBtn = new javax.swing.JButton();
        FunctionsBtn = new javax.swing.JButton();
        Numbers = new javax.swing.JButton();
        StatsBtn = new javax.swing.JButton();
        mainHead = new javax.swing.JLabel();
        jcBtnStat = new javax.swing.JButton();
        jcBtnAlg = new javax.swing.JButton();
        jcBtnNum = new javax.swing.JButton();
        jcBtnFun = new javax.swing.JButton();
        jcBtnExam = new javax.swing.JButton();
        lcBtnAlg = new javax.swing.JButton();
        lcBtnStat = new javax.swing.JButton();
        lcBtnExam = new javax.swing.JButton();
        lcBtnNum = new javax.swing.JButton();
        lcBtnFun = new javax.swing.JButton();
        AlgLbl = new javax.swing.JLabel();
        FunLbl = new javax.swing.JLabel();
        NumLbl = new javax.swing.JLabel();
        StatLbl = new javax.swing.JLabel();
        StatLbl1 = new javax.swing.JLabel();
        ExamLbl = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(200, 100));
        setMaximumSize(new java.awt.Dimension(400, 480));
        setMinimumSize(new java.awt.Dimension(400, 480));
        setPreferredSize(new java.awt.Dimension(400, 500));
        setSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        mainPnl.setLayout(null);

        AlgebraBtn.setBackground(new java.awt.Color(255, 255, 255));
        AlgebraBtn.setText("Algebra");
        AlgebraBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        AlgebraBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        AlgebraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlgebraBtnActionPerformed(evt);
            }
        });
        mainPnl.add(AlgebraBtn);
        AlgebraBtn.setBounds(20, 110, 170, 70);

        FunctionsBtn.setText("Functions");
        FunctionsBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        FunctionsBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        FunctionsBtn.setSize(new java.awt.Dimension(170, 70));
        FunctionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunctionsBtnActionPerformed(evt);
            }
        });
        mainPnl.add(FunctionsBtn);
        FunctionsBtn.setBounds(20, 200, 170, 70);

        Numbers.setText("Numbers");
        Numbers.setMaximumSize(new java.awt.Dimension(95, 23));
        Numbers.setMinimumSize(new java.awt.Dimension(95, 23));
        Numbers.setSize(new java.awt.Dimension(170, 70));
        Numbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumbersActionPerformed(evt);
            }
        });
        mainPnl.add(Numbers);
        Numbers.setBounds(20, 290, 170, 70);

        StatsBtn.setText("Statistics and \nProbability");
        StatsBtn.setMaximumSize(new java.awt.Dimension(95, 23));
        StatsBtn.setMinimumSize(new java.awt.Dimension(95, 23));
        StatsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StatsBtnActionPerformed(evt);
            }
        });
        mainPnl.add(StatsBtn);
        StatsBtn.setBounds(20, 380, 170, 70);

        mainHead.setBackground(new java.awt.Color(0, 0, 0));
        mainHead.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        mainHead.setForeground(new java.awt.Color(255, 255, 255));
        mainHead.setText("Main Menu");
        mainPnl.add(mainHead);
        mainHead.setBounds(140, 20, 170, 50);

        jcBtnStat.setText("Junior Cert");
        jcBtnStat.setMaximumSize(new java.awt.Dimension(95, 23));
        jcBtnStat.setMinimumSize(new java.awt.Dimension(95, 23));
        jcBtnStat.setSize(new java.awt.Dimension(160, 70));
        jcBtnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBtnStatActionPerformed(evt);
            }
        });
        mainPnl.add(jcBtnStat);
        jcBtnStat.setBounds(220, 200, 160, 70);

        jcBtnAlg.setText("Junior Cert");
        jcBtnAlg.setMaximumSize(new java.awt.Dimension(95, 23));
        jcBtnAlg.setMinimumSize(new java.awt.Dimension(95, 23));
        jcBtnAlg.setSize(new java.awt.Dimension(160, 70));
        jcBtnAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBtnAlgActionPerformed(evt);
            }
        });
        mainPnl.add(jcBtnAlg);
        jcBtnAlg.setBounds(220, 200, 160, 70);

        jcBtnNum.setText("Junior Cert");
        jcBtnNum.setMaximumSize(new java.awt.Dimension(95, 23));
        jcBtnNum.setMinimumSize(new java.awt.Dimension(95, 23));
        jcBtnNum.setSize(new java.awt.Dimension(160, 70));
        jcBtnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBtnNumActionPerformed(evt);
            }
        });
        mainPnl.add(jcBtnNum);
        jcBtnNum.setBounds(220, 200, 160, 70);

        jcBtnFun.setText("Junior Cert");
        jcBtnFun.setMaximumSize(new java.awt.Dimension(95, 23));
        jcBtnFun.setMinimumSize(new java.awt.Dimension(95, 23));
        jcBtnFun.setSize(new java.awt.Dimension(160, 70));
        jcBtnFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBtnFunActionPerformed(evt);
            }
        });
        mainPnl.add(jcBtnFun);
        jcBtnFun.setBounds(220, 200, 160, 70);

        jcBtnExam.setText("Junior Cert");
        jcBtnExam.setMaximumSize(new java.awt.Dimension(95, 23));
        jcBtnExam.setMinimumSize(new java.awt.Dimension(95, 23));
        jcBtnExam.setSize(new java.awt.Dimension(160, 70));
        jcBtnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBtnExamActionPerformed(evt);
            }
        });
        mainPnl.add(jcBtnExam);
        jcBtnExam.setBounds(220, 200, 160, 70);

        lcBtnAlg.setText("Leaving Cert");
        lcBtnAlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBtnAlgActionPerformed(evt);
            }
        });
        mainPnl.add(lcBtnAlg);
        lcBtnAlg.setBounds(220, 290, 160, 70);

        lcBtnStat.setText("Leaving Cert");
        lcBtnStat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBtnStatActionPerformed(evt);
            }
        });
        mainPnl.add(lcBtnStat);
        lcBtnStat.setBounds(220, 290, 160, 70);

        lcBtnExam.setText("Leaving Cert");
        lcBtnExam.setSize(new java.awt.Dimension(160, 70));
        lcBtnExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBtnExamActionPerformed(evt);
            }
        });
        mainPnl.add(lcBtnExam);
        lcBtnExam.setBounds(220, 290, 160, 70);

        lcBtnNum.setText("Leaving Cert");
        lcBtnNum.setSize(new java.awt.Dimension(160, 70));
        lcBtnNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBtnNumActionPerformed(evt);
            }
        });
        mainPnl.add(lcBtnNum);
        lcBtnNum.setBounds(220, 290, 160, 70);

        lcBtnFun.setText("Leaving Cert");
        lcBtnFun.setSize(new java.awt.Dimension(160, 70));
        lcBtnFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lcBtnFunActionPerformed(evt);
            }
        });
        mainPnl.add(lcBtnFun);
        lcBtnFun.setBounds(220, 290, 160, 70);

        AlgLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        AlgLbl.setForeground(new java.awt.Color(255, 255, 255));
        AlgLbl.setText("Algebra ");
        mainPnl.add(AlgLbl);
        AlgLbl.setBounds(260, 150, 160, 30);

        FunLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        FunLbl.setForeground(new java.awt.Color(255, 255, 255));
        FunLbl.setText("Functions ");
        mainPnl.add(FunLbl);
        FunLbl.setBounds(250, 150, 180, 30);

        NumLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        NumLbl.setForeground(new java.awt.Color(255, 255, 255));
        NumLbl.setText("Numbers");
        mainPnl.add(NumLbl);
        NumLbl.setBounds(250, 150, 160, 30);

        StatLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        StatLbl.setForeground(new java.awt.Color(255, 255, 255));
        StatLbl.setText("Statistics and ");
        mainPnl.add(StatLbl);
        StatLbl.setBounds(230, 90, 220, 90);

        StatLbl1.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        StatLbl1.setForeground(new java.awt.Color(255, 255, 255));
        StatLbl1.setText("Probability  ");
        mainPnl.add(StatLbl1);
        StatLbl1.setBounds(240, 150, 220, 30);

        ExamLbl.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        ExamLbl.setForeground(new java.awt.Color(255, 255, 255));
        ExamLbl.setText("Exam Papers");
        mainPnl.add(ExamLbl);
        ExamLbl.setBounds(230, 150, 160, 30);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        mainPnl.add(background);
        background.setBounds(0, 0, 400, 480);

        getContentPane().add(mainPnl);
        mainPnl.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    
    private void FunctionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunctionsBtnActionPerformed
        jcBtnFun.setVisible(true);
        lcBtnFun.setVisible(true);
        FunLbl.setVisible(true);
        AlgLbl.setVisible(false); 
        NumLbl.setVisible(false); 
        StatLbl.setVisible(false); 
        StatLbl1.setVisible(false); 
        ExamLbl.setVisible(false);
    }//GEN-LAST:event_FunctionsBtnActionPerformed

    private void jcBtnAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBtnAlgActionPerformed
       this.setVisible(false);
        new AlgebraJC().setVisible(true);
    }//GEN-LAST:event_jcBtnAlgActionPerformed

    private void StatsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StatsBtnActionPerformed
       jcBtnStat.setVisible(true);
        lcBtnStat.setVisible(true);
        StatLbl.setVisible(true);
        StatLbl1.setVisible(true);
        AlgLbl.setVisible(false); 
        FunLbl.setVisible(false); 
        NumLbl.setVisible(false); 
        ExamLbl.setVisible(false);
        
        
    }//GEN-LAST:event_StatsBtnActionPerformed

    private void jcBtnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBtnStatActionPerformed
        this.setVisible(false);
        new StatsAndProbJC().setVisible(true);
    }//GEN-LAST:event_jcBtnStatActionPerformed

    private void jcBtnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBtnNumActionPerformed
       this.setVisible(false);
        new NumberJC().setVisible(true);
    }//GEN-LAST:event_jcBtnNumActionPerformed

    private void jcBtnFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBtnFunActionPerformed
        this.setVisible(false);
        new FunctionsJC().setVisible(true);
    }//GEN-LAST:event_jcBtnFunActionPerformed

    private void lcBtnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBtnExamActionPerformed
       this.setVisible(false);
       new ExamPapers().setVisible(true);
    }//GEN-LAST:event_lcBtnExamActionPerformed

    private void lcBtnNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBtnNumActionPerformed
        this.setVisible(false);
        new NumberLC().setVisible(true);
    }//GEN-LAST:event_lcBtnNumActionPerformed

    private void lcBtnFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBtnFunActionPerformed
       this.setVisible(false);
       new FunctionsLC().setVisible(true);
    }//GEN-LAST:event_lcBtnFunActionPerformed

    private void jcBtnExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBtnExamActionPerformed
       this.setVisible(false);
       new ExamPapers().setVisible(true);
    }//GEN-LAST:event_jcBtnExamActionPerformed

    private void NumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumbersActionPerformed
       jcBtnNum.setVisible(true);
        lcBtnNum.setVisible(true);
        NumLbl.setVisible(true);
        AlgLbl.setVisible(false); 
        FunLbl.setVisible(false); 
        StatLbl.setVisible(false); 
        StatLbl1.setVisible(false); 
        ExamLbl.setVisible(false);
    }//GEN-LAST:event_NumbersActionPerformed

    private void AlgebraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlgebraBtnActionPerformed
        jcBtnAlg.setVisible(true);
        lcBtnAlg.setVisible(true);
        AlgLbl.setVisible(true);

        FunLbl.setVisible(false);
        NumLbl.setVisible(false);
        StatLbl.setVisible(false);
        StatLbl1.setVisible(false);
        ExamLbl.setVisible(false);
    }//GEN-LAST:event_AlgebraBtnActionPerformed

    private void lcBtnStatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBtnStatActionPerformed
        this.setVisible(false);
        new StatsAndProbLC().setVisible(true);
    }//GEN-LAST:event_lcBtnStatActionPerformed

    private void lcBtnAlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lcBtnAlgActionPerformed
        this.setVisible(false);
        new AlgebraLC().setVisible(true);
    }//GEN-LAST:event_lcBtnAlgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlgLbl;
    private javax.swing.JButton AlgebraBtn;
    private javax.swing.JLabel ExamLbl;
    private javax.swing.JLabel FunLbl;
    private javax.swing.JButton FunctionsBtn;
    private javax.swing.JLabel NumLbl;
    private javax.swing.JButton Numbers;
    private javax.swing.JLabel StatLbl;
    private javax.swing.JLabel StatLbl1;
    private javax.swing.JButton StatsBtn;
    private javax.swing.JLabel background;
    private javax.swing.JButton jcBtnAlg;
    private javax.swing.JButton jcBtnExam;
    private javax.swing.JButton jcBtnFun;
    private javax.swing.JButton jcBtnNum;
    private javax.swing.JButton jcBtnStat;
    private javax.swing.JButton lcBtnAlg;
    private javax.swing.JButton lcBtnExam;
    private javax.swing.JButton lcBtnFun;
    private javax.swing.JButton lcBtnNum;
    private javax.swing.JButton lcBtnStat;
    private javax.swing.JLabel mainHead;
    private javax.swing.JPanel mainPnl;
    // End of variables declaration//GEN-END:variables
}
