/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectgui;

import javax.swing.JOptionPane;

/**
 *
 * @author x14472008
 */
public class NumberJC extends javax.swing.JFrame {

    /**
     * Creates new form statsAndFun
     */
    public NumberJC() {
        initComponents();
        HighlvlStats.setVisible(false);
        OrdinarylvlStats.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        StatsPnlJC = new javax.swing.JPanel();
        headLbl = new javax.swing.JLabel();
        headLbl2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        highBtn = new javax.swing.JButton();
        ordBtn = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        DevBtn = new javax.swing.JButton();
        ordHomeMain = new javax.swing.JButton();
        background = new javax.swing.JLabel();
        OrdinarylvlStats = new javax.swing.JPanel();
        question1 = new javax.swing.JPanel();
        jTextArea3 = new javax.swing.JTextArea();
        ordHead1 = new javax.swing.JLabel();
        calc2 = new javax.swing.JButton();
        answer2w = new javax.swing.JRadioButton();
        answer1w = new javax.swing.JRadioButton();
        answer3c = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        ordHome1 = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        question2 = new javax.swing.JPanel();
        jTextArea4 = new javax.swing.JTextArea();
        ordHead2 = new javax.swing.JLabel();
        calc4 = new javax.swing.JButton();
        answerw2w = new javax.swing.JRadioButton();
        answer1w1 = new javax.swing.JRadioButton();
        answer3c1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        ordHome2 = new javax.swing.JButton();
        backBtn4 = new javax.swing.JButton();
        background6 = new javax.swing.JLabel();
        question3 = new javax.swing.JPanel();
        jTextArea5 = new javax.swing.JTextArea();
        ordHead3 = new javax.swing.JLabel();
        calc5 = new javax.swing.JButton();
        answer22w = new javax.swing.JRadioButton();
        answer11w = new javax.swing.JRadioButton();
        answer33c = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        ordHome3 = new javax.swing.JButton();
        backBtn5 = new javax.swing.JButton();
        background5 = new javax.swing.JLabel();
        HighlvlStats = new javax.swing.JPanel();
        question4 = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        ordHead6 = new javax.swing.JLabel();
        calc3 = new javax.swing.JButton();
        answer4c = new javax.swing.JRadioButton();
        answer4w = new javax.swing.JRadioButton();
        answer44w = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        ordHome6 = new javax.swing.JButton();
        backBtn6 = new javax.swing.JButton();
        background10 = new javax.swing.JLabel();
        question5 = new javax.swing.JPanel();
        jTextArea8 = new javax.swing.JTextArea();
        ordHead7 = new javax.swing.JLabel();
        calc8 = new javax.swing.JButton();
        answer55w = new javax.swing.JRadioButton();
        answer5w = new javax.swing.JRadioButton();
        answer5c = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        ordHome7 = new javax.swing.JButton();
        backBtn9 = new javax.swing.JButton();
        background11 = new javax.swing.JLabel();
        question6 = new javax.swing.JPanel();
        jTextArea9 = new javax.swing.JTextArea();
        ordHead8 = new javax.swing.JLabel();
        calc9 = new javax.swing.JButton();
        answer66w = new javax.swing.JRadioButton();
        answer6c = new javax.swing.JRadioButton();
        answer6w = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        ordHome8 = new javax.swing.JButton();
        backBtn10 = new javax.swing.JButton();
        background12 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 480));
        getContentPane().setLayout(null);

        StatsPnlJC.setLayout(null);

        headLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headLbl.setForeground(new java.awt.Color(240, 240, 240));
        headLbl.setText("Numbers");
        StatsPnlJC.add(headLbl);
        headLbl.setBounds(140, 10, 310, 50);

        headLbl2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headLbl2.setForeground(new java.awt.Color(255, 255, 255));
        headLbl2.setText("Junior Cert");
        StatsPnlJC.add(headLbl2);
        headLbl2.setBounds(170, 80, 70, 30);

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(backBtn);
        backBtn.setBounds(20, 420, 110, 40);

        highBtn.setText("Higher Level");
        highBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(highBtn);
        highBtn.setBounds(120, 130, 160, 70);

        ordBtn.setText("Ordinary Level");
        ordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(ordBtn);
        ordBtn.setBounds(120, 240, 160, 70);

        calc.setText("Calculator");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        StatsPnlJC.add(calc);
        calc.setBounds(280, 420, 110, 40);

        DevBtn.setText("Developer");
        DevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtnActionPerformed(evt);
            }
        });
        StatsPnlJC.add(DevBtn);
        DevBtn.setBounds(150, 370, 110, 25);

        ordHomeMain.setText("Home");
        ordHomeMain.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMainActionPerformed(evt);
            }
        });
        StatsPnlJC.add(ordHomeMain);
        ordHomeMain.setBounds(150, 420, 110, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        StatsPnlJC.add(background);
        background.setBounds(0, 0, 400, 480);

        getContentPane().add(StatsPnlJC);
        StatsPnlJC.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.setLayout(null);

        question1.setLayout(null);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("What is the Greatest Common Factor of 36 \nand 54. Hint: List all the factors of both \nnumbers first.");
        question1.add(jTextArea3);
        jTextArea3.setBounds(30, 70, 350, 80);

        ordHead1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead1.setForeground(new java.awt.Color(255, 255, 255));
        ordHead1.setText("Ordinary Level");
        question1.add(ordHead1);
        ordHead1.setBounds(110, 40, 200, 20);

        calc2.setText("Calculator");
        calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc2ActionPerformed(evt);
            }
        });
        question1.add(calc2);
        calc2.setBounds(280, 420, 110, 40);

        answer2w.setText("C:18");
        answer2w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2wActionPerformed(evt);
            }
        });
        question1.add(answer2w);
        answer2w.setBounds(140, 290, 70, 23);

        answer1w.setText("A:12");
        answer1w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1wActionPerformed(evt);
            }
        });
        question1.add(answer1w);
        answer1w.setBounds(140, 190, 70, 23);

        answer3c.setText("B:36");
        question1.add(answer3c);
        answer3c.setBounds(140, 240, 70, 23);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        question1.add(jButton2);
        jButton2.setBounds(120, 360, 140, 40);

        ordHome1.setText("Home");
        ordHome1.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome1ActionPerformed(evt);
            }
        });
        question1.add(ordHome1);
        ordHome1.setBounds(150, 420, 110, 40);

        backBtn3.setText("Back");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });
        question1.add(backBtn3);
        backBtn3.setBounds(20, 420, 110, 40);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question1.add(background3);
        background3.setBounds(0, -10, 400, 480);

        OrdinarylvlStats.add(question1);
        question1.setBounds(0, 0, 400, 480);

        question2.setLayout(null);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("The Least Common Multiple is the smallest \nnumber that two or more numbers will \ndivide into evenly. What is the Least \nCommon Multiple of 12 and 15?");
        question2.add(jTextArea4);
        jTextArea4.setBounds(30, 30, 350, 110);

        ordHead2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead2.setForeground(new java.awt.Color(255, 255, 255));
        ordHead2.setText("Ordinary Level");
        question2.add(ordHead2);
        ordHead2.setBounds(100, 10, 200, 20);

        calc4.setText("Calculator");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });
        question2.add(calc4);
        calc4.setBounds(280, 420, 110, 40);

        answerw2w.setText("C:60");
        answerw2w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerw2wActionPerformed(evt);
            }
        });
        question2.add(answerw2w);
        answerw2w.setBounds(150, 270, 80, 23);

        answer1w1.setText("A:3");
        answer1w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1w1ActionPerformed(evt);
            }
        });
        question2.add(answer1w1);
        answer1w1.setBounds(150, 180, 80, 23);

        answer3c1.setText("B:30");
        question2.add(answer3c1);
        answer3c1.setBounds(150, 220, 80, 23);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        question2.add(jButton3);
        jButton3.setBounds(130, 340, 140, 40);

        ordHome2.setText("Home");
        ordHome2.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome2ActionPerformed(evt);
            }
        });
        question2.add(ordHome2);
        ordHome2.setBounds(150, 420, 110, 40);

        backBtn4.setText("Back");
        backBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn4ActionPerformed(evt);
            }
        });
        question2.add(backBtn4);
        backBtn4.setBounds(20, 420, 110, 40);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question2.add(background6);
        background6.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(question2);
        question2.setBounds(0, 0, 400, 480);

        question3.setLayout(null);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("Place the following numbers in order from \nleast to greatest: 0.276, 1/9, 0.023, 5/6\n");
        question3.add(jTextArea5);
        jTextArea5.setBounds(30, 70, 350, 80);

        ordHead3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead3.setForeground(new java.awt.Color(255, 255, 255));
        ordHead3.setText("Ordinary Level");
        question3.add(ordHead3);
        ordHead3.setBounds(110, 40, 200, 20);

        calc5.setText("Calculator");
        calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc5ActionPerformed(evt);
            }
        });
        question3.add(calc5);
        calc5.setBounds(280, 420, 110, 40);

        answer22w.setText("C:0.276, 0.023, 1/9, 5/6");
        answer22w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer22wActionPerformed(evt);
            }
        });
        question3.add(answer22w);
        answer22w.setBounds(110, 290, 160, 23);

        answer11w.setText("A: 0.023, 1/9, 0.276, 5/6");
        answer11w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer11wActionPerformed(evt);
            }
        });
        question3.add(answer11w);
        answer11w.setBounds(110, 190, 160, 23);

        answer33c.setText("B: 1/9, 0.023, 0.276, 5/6");
        question3.add(answer33c);
        answer33c.setBounds(110, 240, 160, 23);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        question3.add(jButton4);
        jButton4.setBounds(120, 360, 140, 40);

        ordHome3.setText("Home");
        ordHome3.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome3ActionPerformed(evt);
            }
        });
        question3.add(ordHome3);
        ordHome3.setBounds(150, 420, 110, 40);

        backBtn5.setText("Back");
        backBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn5ActionPerformed(evt);
            }
        });
        question3.add(backBtn5);
        backBtn5.setBounds(20, 420, 110, 40);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question3.add(background5);
        background5.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(question3);
        question3.setBounds(0, 0, 400, 480);

        getContentPane().add(OrdinarylvlStats);
        OrdinarylvlStats.setBounds(0, 0, 400, 480);

        HighlvlStats.setLayout(null);

        question4.setLayout(null);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Mary, Kelly, and Becky are all selling \ncandy at a school candy fundraiser. Mary \nsold 20 pieces of candy, Kelly sold 25 \npieces of candy, and Becky sold 15 pieces \nof candy. They were able to sell 2/3 of \nthe total number of pieces of candy that \nthey had prepared for the sale. What was \nthe total number of pieces of candy that \nthey had brought to sell at the fundraiser?\n");
        question4.add(jTextArea2);
        jTextArea2.setBounds(30, 70, 350, 190);

        ordHead6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead6.setForeground(new java.awt.Color(255, 255, 255));
        ordHead6.setText("Higiher Level");
        question4.add(ordHead6);
        ordHead6.setBounds(110, 40, 200, 20);

        calc3.setText("Calculator");
        calc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc3ActionPerformed(evt);
            }
        });
        question4.add(calc3);
        calc3.setBounds(280, 420, 110, 40);

        answer4c.setText("C:90");
        answer4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4cActionPerformed(evt);
            }
        });
        question4.add(answer4c);
        answer4c.setBounds(140, 330, 100, 23);

        answer4w.setText("A: 20");
        answer4w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4wActionPerformed(evt);
            }
        });
        question4.add(answer4w);
        answer4w.setBounds(140, 270, 100, 23);

        answer44w.setText("B:60");
        question4.add(answer44w);
        answer44w.setBounds(140, 300, 100, 23);

        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        question4.add(jButton8);
        jButton8.setBounds(120, 360, 140, 40);

        ordHome6.setText("Home");
        ordHome6.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome6ActionPerformed(evt);
            }
        });
        question4.add(ordHome6);
        ordHome6.setBounds(150, 420, 110, 40);

        backBtn6.setText("Back");
        backBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn6ActionPerformed(evt);
            }
        });
        question4.add(backBtn6);
        backBtn6.setBounds(20, 420, 110, 40);

        background10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question4.add(background10);
        background10.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question4);
        question4.setBounds(0, 0, 400, 480);

        question5.setLayout(null);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("What is the result when you add the \nfollowing numbers? 0.52 + 3 + 2.42");
        question5.add(jTextArea8);
        jTextArea8.setBounds(30, 50, 350, 90);

        ordHead7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead7.setForeground(new java.awt.Color(255, 255, 255));
        ordHead7.setText("Higher Level");
        question5.add(ordHead7);
        ordHead7.setBounds(100, 10, 200, 20);

        calc8.setText("Calculator");
        calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc8ActionPerformed(evt);
            }
        });
        question5.add(calc8);
        calc8.setBounds(280, 420, 110, 40);

        answer55w.setText("C:10.62");
        answer55w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer55wActionPerformed(evt);
            }
        });
        question5.add(answer55w);
        answer55w.setBounds(150, 280, 80, 23);

        answer5w.setText("A:6.00");
        answer5w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer5wActionPerformed(evt);
            }
        });
        question5.add(answer5w);
        answer5w.setBounds(150, 180, 80, 23);

        answer5c.setText("B:5.94");
        question5.add(answer5c);
        answer5c.setBounds(150, 230, 80, 23);

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        question5.add(jButton9);
        jButton9.setBounds(130, 370, 140, 40);

        ordHome7.setText("Home");
        ordHome7.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome7ActionPerformed(evt);
            }
        });
        question5.add(ordHome7);
        ordHome7.setBounds(150, 420, 110, 40);

        backBtn9.setText("Back");
        backBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn9ActionPerformed(evt);
            }
        });
        question5.add(backBtn9);
        backBtn9.setBounds(20, 420, 110, 40);

        background11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question5.add(background11);
        background11.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question5);
        question5.setBounds(0, 0, 400, 480);

        question6.setLayout(null);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Can you order the following numbers from \nGREATEST TO LEAST using the greater than \nand less than symbols? 45,999 54,923 223,\n564 1,344,534");
        question6.add(jTextArea9);
        jTextArea9.setBounds(30, 60, 350, 130);

        ordHead8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead8.setForeground(new java.awt.Color(255, 255, 255));
        ordHead8.setText("Higher Level");
        question6.add(ordHead8);
        ordHead8.setBounds(110, 40, 200, 20);

        calc9.setText("Calculator");
        calc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc9ActionPerformed(evt);
            }
        });
        question6.add(calc9);
        calc9.setBounds(280, 420, 110, 40);

        answer66w.setText("C:45,99>54,923>223,564>1,344,524");
        answer66w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer66wActionPerformed(evt);
            }
        });
        question6.add(answer66w);
        answer66w.setBounds(80, 290, 230, 23);

        answer6c.setText("A:1,344,524>223,564>54,923>45,999");
        answer6c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer6cActionPerformed(evt);
            }
        });
        question6.add(answer6c);
        answer6c.setBounds(80, 200, 230, 23);

        answer6w.setText("B: 223,564>54,923>45,999>1,344,524");
        question6.add(answer6w);
        answer6w.setBounds(80, 240, 230, 23);

        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        question6.add(jButton10);
        jButton10.setBounds(120, 360, 140, 40);

        ordHome8.setText("Home");
        ordHome8.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome8ActionPerformed(evt);
            }
        });
        question6.add(ordHome8);
        ordHome8.setBounds(150, 420, 110, 40);

        backBtn10.setText("Back");
        backBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn10ActionPerformed(evt);
            }
        });
        question6.add(backBtn10);
        backBtn10.setBounds(20, 420, 110, 40);

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question6.add(background12);
        background12.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question6);
        question6.setBounds(0, 0, 400, 480);

        getContentPane().add(HighlvlStats);
        HighlvlStats.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtnActionPerformed

    private void ordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordBtnActionPerformed
        StatsPnlJC.setVisible(false);
       OrdinarylvlStats.setVisible(true);
    }//GEN-LAST:event_ordBtnActionPerformed

    private void highBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highBtnActionPerformed
       StatsPnlJC.setVisible(false);
       HighlvlStats.setVisible(true);
    }//GEN-LAST:event_highBtnActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
       new Calculator().setVisible(true);
    }//GEN-LAST:event_calcActionPerformed

    private void ordHomeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMainActionPerformed
       this.setVisible(false);
       new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMainActionPerformed

    private void DevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtnActionPerformed
        this.setVisible(false);
        new QuestionGUI().setVisible(true);

    }//GEN-LAST:event_DevBtnActionPerformed

    private void calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc2ActionPerformed

    private void answer2wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2wActionPerformed

    private void answer1wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1wActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        boolean answer = false;
        if(answer1w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer2w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(true);
            question3.setVisible(false);
        }
        else {
            question2.setVisible(true); }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void ordHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome1ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHome1ActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        OrdinarylvlStats.setVisible(false);
        StatsPnlJC.setVisible(true);
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc4ActionPerformed

    private void answerw2wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerw2wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerw2wActionPerformed

    private void answer1w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1w1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1w1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean answer = false;
        if(answerw2w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer1w1.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(false);
            question3.setVisible(true);
        }
        else {
            question2.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ordHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome2ActionPerformed

    private void backBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn4ActionPerformed

    private void calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc5ActionPerformed

    private void answer22wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer22wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer22wActionPerformed

    private void answer11wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer11wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer11wActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        boolean answer = false;
        if(answer11w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer22w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(false);
            question3.setVisible(true);
            StatsPnlJC.setVisible(true);
        }
        else {
            question3.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ordHome3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome3ActionPerformed

    private void backBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn5ActionPerformed

    private void calc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc3ActionPerformed

    private void answer4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4cActionPerformed

    private void answer4wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4wActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO boolean answer=false;
        boolean answer = false;

        if(answer4w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer44w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(true);
            question6.setVisible(false);
        }
        else {
            question5.setVisible(true);
        }

        // TODO add your handling code here:

    }//GEN-LAST:event_jButton8ActionPerformed

    private void ordHome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome6ActionPerformed

    private void backBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn6ActionPerformed

    private void calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc8ActionPerformed

    private void answer55wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer55wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer55wActionPerformed

    private void answer5wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer5wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer5wActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //  boolean answer = false;
        boolean answer = false;

        if(answer5w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer55w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(false);
            question6.setVisible(true);
        }
        else {
            question6.setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ordHome7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome7ActionPerformed

    private void backBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn9ActionPerformed

    private void calc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc9ActionPerformed

    private void answer66wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer66wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer66wActionPerformed

    private void answer6cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer6cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer6cActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        boolean answer = false ;

        if(answer6w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer66w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(false);
            question6.setVisible(true);
            StatsPnlJC.setVisible(true);
        }
        else {
            question6.setVisible(true);
        }

    }//GEN-LAST:event_jButton10ActionPerformed

    private void ordHome8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome8ActionPerformed

    private void backBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberJC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberJC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DevBtn;
    private javax.swing.JPanel HighlvlStats;
    private javax.swing.JPanel OrdinarylvlStats;
    private javax.swing.JPanel StatsPnlJC;
    private javax.swing.JRadioButton answer11w;
    private javax.swing.JRadioButton answer1w;
    private javax.swing.JRadioButton answer1w1;
    private javax.swing.JRadioButton answer22w;
    private javax.swing.JRadioButton answer2w;
    private javax.swing.JRadioButton answer33c;
    private javax.swing.JRadioButton answer3c;
    private javax.swing.JRadioButton answer3c1;
    private javax.swing.JRadioButton answer44w;
    private javax.swing.JRadioButton answer4c;
    private javax.swing.JRadioButton answer4w;
    private javax.swing.JRadioButton answer55w;
    private javax.swing.JRadioButton answer5c;
    private javax.swing.JRadioButton answer5w;
    private javax.swing.JRadioButton answer66w;
    private javax.swing.JRadioButton answer6c;
    private javax.swing.JRadioButton answer6w;
    private javax.swing.JRadioButton answerw2w;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn10;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn4;
    private javax.swing.JButton backBtn5;
    private javax.swing.JButton backBtn6;
    private javax.swing.JButton backBtn9;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background10;
    private javax.swing.JLabel background11;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JButton calc;
    private javax.swing.JButton calc2;
    private javax.swing.JButton calc3;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc5;
    private javax.swing.JButton calc8;
    private javax.swing.JButton calc9;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel headLbl2;
    private javax.swing.JButton highBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JButton ordBtn;
    private javax.swing.JLabel ordHead1;
    private javax.swing.JLabel ordHead2;
    private javax.swing.JLabel ordHead3;
    private javax.swing.JLabel ordHead6;
    private javax.swing.JLabel ordHead7;
    private javax.swing.JLabel ordHead8;
    private javax.swing.JButton ordHome1;
    private javax.swing.JButton ordHome2;
    private javax.swing.JButton ordHome3;
    private javax.swing.JButton ordHome6;
    private javax.swing.JButton ordHome7;
    private javax.swing.JButton ordHome8;
    private javax.swing.JButton ordHomeMain;
    private javax.swing.JPanel question1;
    private javax.swing.JPanel question2;
    private javax.swing.JPanel question3;
    private javax.swing.JPanel question4;
    private javax.swing.JPanel question5;
    private javax.swing.JPanel question6;
    // End of variables declaration//GEN-END:variables
}
