/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectgui;

import javax.swing.JOptionPane;

/**
 *
 * @author x14472008
 */
public class NumberLC extends javax.swing.JFrame {

    /**
     * Creates new form statsAndFun
     */
    public NumberLC() {
        initComponents();
        question1.setVisible(false);
        question2.setVisible(false);
        question3.setVisible(false);
        question4.setVisible(false);
        question5.setVisible(false);
        question6.setVisible(false);
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        NumbersPnl = new javax.swing.JPanel();
        headLbl1 = new javax.swing.JLabel();
        headLbl3 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        highBtn1 = new javax.swing.JButton();
        ordBtn1 = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        ordHomeMain = new javax.swing.JButton();
        DevBtn = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        OrdinarylvlStats = new javax.swing.JPanel();
        question1 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        ordHead = new javax.swing.JLabel();
        calc1 = new javax.swing.JButton();
        answer2w = new javax.swing.JRadioButton();
        answer1w = new javax.swing.JRadioButton();
        answer3c = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        ordHome = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();
        question2 = new javax.swing.JPanel();
        jTextArea3 = new javax.swing.JTextArea();
        ordHead2 = new javax.swing.JLabel();
        calc2 = new javax.swing.JButton();
        answerw2w = new javax.swing.JRadioButton();
        answer1w1 = new javax.swing.JRadioButton();
        answer3c1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        ordHome1 = new javax.swing.JButton();
        backBtn4 = new javax.swing.JButton();
        background6 = new javax.swing.JLabel();
        question3 = new javax.swing.JPanel();
        jTextArea4 = new javax.swing.JTextArea();
        ordHead3 = new javax.swing.JLabel();
        calc4 = new javax.swing.JButton();
        answer22w = new javax.swing.JRadioButton();
        answer11w = new javax.swing.JRadioButton();
        answer33c = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        ordHome2 = new javax.swing.JButton();
        backBtn5 = new javax.swing.JButton();
        background5 = new javax.swing.JLabel();
        HighlvlStats = new javax.swing.JPanel();
        question4 = new javax.swing.JPanel();
        jTextArea2 = new javax.swing.JTextArea();
        ordHead6 = new javax.swing.JLabel();
        calc3 = new javax.swing.JButton();
        answer4c = new javax.swing.JRadioButton();
        answer4w = new javax.swing.JRadioButton();
        answer44w = new javax.swing.JRadioButton();
        jButton8 = new javax.swing.JButton();
        ordHome6 = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        background10 = new javax.swing.JLabel();
        question5 = new javax.swing.JPanel();
        jTextArea8 = new javax.swing.JTextArea();
        ordHead7 = new javax.swing.JLabel();
        calc8 = new javax.swing.JButton();
        answer55w = new javax.swing.JRadioButton();
        answer5w = new javax.swing.JRadioButton();
        answer5c = new javax.swing.JRadioButton();
        jButton9 = new javax.swing.JButton();
        ordHome7 = new javax.swing.JButton();
        backBtn9 = new javax.swing.JButton();
        background11 = new javax.swing.JLabel();
        question6 = new javax.swing.JPanel();
        jTextArea9 = new javax.swing.JTextArea();
        ordHead8 = new javax.swing.JLabel();
        calc9 = new javax.swing.JButton();
        answer66w = new javax.swing.JRadioButton();
        answer6c = new javax.swing.JRadioButton();
        answer6w = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        ordHome8 = new javax.swing.JButton();
        backBtn10 = new javax.swing.JButton();
        background12 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 480));
        getContentPane().setLayout(null);

        NumbersPnl.setLayout(null);

        headLbl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headLbl1.setForeground(new java.awt.Color(240, 240, 240));
        headLbl1.setText("Numbers");
        NumbersPnl.add(headLbl1);
        headLbl1.setBounds(140, 10, 310, 50);

        headLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headLbl3.setForeground(new java.awt.Color(255, 255, 255));
        headLbl3.setText("Leaving Cert");
        NumbersPnl.add(headLbl3);
        headLbl3.setBounds(150, 80, 80, 20);

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        NumbersPnl.add(backBtn1);
        backBtn1.setBounds(20, 420, 110, 40);

        highBtn1.setText("Higher Level");
        highBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highBtn1ActionPerformed(evt);
            }
        });
        NumbersPnl.add(highBtn1);
        highBtn1.setBounds(120, 130, 160, 70);

        ordBtn1.setText("Ordinary Level");
        ordBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordBtn1ActionPerformed(evt);
            }
        });
        NumbersPnl.add(ordBtn1);
        ordBtn1.setBounds(120, 240, 160, 70);

        calc.setText("Calculator");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        NumbersPnl.add(calc);
        calc.setBounds(280, 420, 110, 40);

        ordHomeMain.setText("Home");
        ordHomeMain.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMainActionPerformed(evt);
            }
        });
        NumbersPnl.add(ordHomeMain);
        ordHomeMain.setBounds(150, 420, 110, 40);

        DevBtn.setText("Developer");
        DevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtnActionPerformed(evt);
            }
        });
        NumbersPnl.add(DevBtn);
        DevBtn.setBounds(150, 370, 110, 25);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        NumbersPnl.add(background3);
        background3.setBounds(0, 0, 400, 480);

        getContentPane().add(NumbersPnl);
        NumbersPnl.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.setLayout(null);

        question1.setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Simplify the expression below using the\nrules of the Order of Operations. 5+3(2+8)\n\n");
        question1.add(jTextArea1);
        jTextArea1.setBounds(30, 70, 350, 80);

        ordHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead.setForeground(new java.awt.Color(255, 255, 255));
        ordHead.setText("Ordinary Level");
        question1.add(ordHead);
        ordHead.setBounds(110, 40, 200, 20);

        calc1.setText("Calculator");
        calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc1ActionPerformed(evt);
            }
        });
        question1.add(calc1);
        calc1.setBounds(280, 420, 110, 40);

        answer2w.setText("C:18");
        answer2w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer2wActionPerformed(evt);
            }
        });
        question1.add(answer2w);
        answer2w.setBounds(140, 290, 70, 23);

        answer1w.setText("A:35");
        answer1w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1wActionPerformed(evt);
            }
        });
        question1.add(answer1w);
        answer1w.setBounds(140, 190, 70, 23);

        answer3c.setText("B:80");
        question1.add(answer3c);
        answer3c.setBounds(140, 240, 70, 23);

        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        question1.add(jButton2);
        jButton2.setBounds(120, 360, 140, 40);

        ordHome.setText("Home");
        ordHome.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeActionPerformed(evt);
            }
        });
        question1.add(ordHome);
        ordHome.setBounds(150, 420, 110, 40);

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });
        question1.add(backBtn2);
        backBtn2.setBounds(20, 420, 110, 40);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question1.add(background2);
        background2.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(question1);
        question1.setBounds(0, 0, 400, 480);

        question2.setLayout(null);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("One Saturday, \nan electronics store gave away free \nmini-ipods to any customer who purchased \nmerchandise totalling over $1,000. \nIf there were a total of 26 purchases \ntotalling over $1,000 that Saturday, \nwhat is the integer that represents the \nchange in number of free mini-ipods the \nstore had in stock at the end of the day \nSaturday?");
        question2.add(jTextArea3);
        jTextArea3.setBounds(30, 30, 350, 210);

        ordHead2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead2.setForeground(new java.awt.Color(255, 255, 255));
        ordHead2.setText("Ordinary Level");
        question2.add(ordHead2);
        ordHead2.setBounds(100, 10, 200, 20);

        calc2.setText("Calculator");
        calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc2ActionPerformed(evt);
            }
        });
        question2.add(calc2);
        calc2.setBounds(280, 420, 110, 40);

        answerw2w.setText("C:26");
        answerw2w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerw2wActionPerformed(evt);
            }
        });
        question2.add(answerw2w);
        answerw2w.setBounds(150, 310, 80, 23);

        answer1w1.setText("A:1000");
        answer1w1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer1w1ActionPerformed(evt);
            }
        });
        question2.add(answer1w1);
        answer1w1.setBounds(150, 250, 80, 23);

        answer3c1.setText("B:11000");
        question2.add(answer3c1);
        answer3c1.setBounds(150, 280, 80, 23);

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        question2.add(jButton3);
        jButton3.setBounds(130, 370, 140, 40);

        ordHome1.setText("Home");
        ordHome1.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome1ActionPerformed(evt);
            }
        });
        question2.add(ordHome1);
        ordHome1.setBounds(150, 420, 110, 40);

        backBtn4.setText("Back");
        backBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn4ActionPerformed(evt);
            }
        });
        question2.add(backBtn4);
        backBtn4.setBounds(20, 420, 110, 40);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question2.add(background6);
        background6.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(question2);
        question2.setBounds(0, 0, 400, 480);

        question3.setLayout(null);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("What is the prime factorization of the \ninteger 210?");
        question3.add(jTextArea4);
        jTextArea4.setBounds(30, 70, 350, 80);

        ordHead3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead3.setForeground(new java.awt.Color(255, 255, 255));
        ordHead3.setText("Ordinary Level");
        question3.add(ordHead3);
        ordHead3.setBounds(110, 40, 200, 20);

        calc4.setText("Calculator");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });
        question3.add(calc4);
        calc4.setBounds(280, 420, 110, 40);

        answer22w.setText("C: 10x21");
        answer22w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer22wActionPerformed(evt);
            }
        });
        question3.add(answer22w);
        answer22w.setBounds(140, 290, 70, 23);

        answer11w.setText("A: 5x6x7");
        answer11w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer11wActionPerformed(evt);
            }
        });
        question3.add(answer11w);
        answer11w.setBounds(140, 190, 70, 23);

        answer33c.setText("B: 2x3x5x7");
        question3.add(answer33c);
        answer33c.setBounds(140, 240, 70, 23);

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        question3.add(jButton4);
        jButton4.setBounds(120, 360, 140, 40);

        ordHome2.setText("Home");
        ordHome2.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome2ActionPerformed(evt);
            }
        });
        question3.add(ordHome2);
        ordHome2.setBounds(150, 420, 110, 40);

        backBtn5.setText("Back");
        backBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn5ActionPerformed(evt);
            }
        });
        question3.add(backBtn5);
        backBtn5.setBounds(20, 420, 110, 40);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question3.add(background5);
        background5.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(question3);
        question3.setBounds(0, 0, 400, 480);

        getContentPane().add(OrdinarylvlStats);
        OrdinarylvlStats.setBounds(0, 0, 400, 480);

        HighlvlStats.setLayout(null);

        question4.setLayout(null);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Which of the numbers below represents the \nfollowing: Six million, four hundred \nsixty-two thousand, three hundred fifty-one.");
        question4.add(jTextArea2);
        jTextArea2.setBounds(30, 70, 350, 80);

        ordHead6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead6.setForeground(new java.awt.Color(255, 255, 255));
        ordHead6.setText("Higiher Level");
        question4.add(ordHead6);
        ordHead6.setBounds(110, 40, 200, 20);

        calc3.setText("Calculator");
        calc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc3ActionPerformed(evt);
            }
        });
        question4.add(calc3);
        calc3.setBounds(280, 420, 110, 40);

        answer4c.setText("C:6,462,351");
        answer4c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4cActionPerformed(evt);
            }
        });
        question4.add(answer4c);
        answer4c.setBounds(140, 290, 100, 23);

        answer4w.setText("A: 6,351,462");
        answer4w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer4wActionPerformed(evt);
            }
        });
        question4.add(answer4w);
        answer4w.setBounds(140, 190, 100, 23);

        answer44w.setText("B:6,462,000");
        question4.add(answer44w);
        answer44w.setBounds(140, 240, 100, 23);

        jButton8.setText("Submit");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        question4.add(jButton8);
        jButton8.setBounds(120, 360, 140, 40);

        ordHome6.setText("Home");
        ordHome6.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome6ActionPerformed(evt);
            }
        });
        question4.add(ordHome6);
        ordHome6.setBounds(150, 420, 110, 40);

        backBtn3.setText("Back");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });
        question4.add(backBtn3);
        backBtn3.setBounds(20, 420, 110, 40);

        background10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question4.add(background10);
        background10.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question4);
        question4.setBounds(0, 0, 400, 480);

        question5.setLayout(null);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Compare the following numbers and use \nsymbols to show the relationship. \n4,912,641 4,931,221");
        question5.add(jTextArea8);
        jTextArea8.setBounds(30, 50, 350, 90);

        ordHead7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead7.setForeground(new java.awt.Color(255, 255, 255));
        ordHead7.setText("Higher Level");
        question5.add(ordHead7);
        ordHead7.setBounds(100, 10, 200, 20);

        calc8.setText("Calculator");
        calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc8ActionPerformed(evt);
            }
        });
        question5.add(calc8);
        calc8.setBounds(280, 420, 110, 40);

        answer55w.setText("C: =");
        answer55w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer55wActionPerformed(evt);
            }
        });
        question5.add(answer55w);
        answer55w.setBounds(150, 250, 80, 23);

        answer5w.setText("A:>");
        answer5w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer5wActionPerformed(evt);
            }
        });
        question5.add(answer5w);
        answer5w.setBounds(150, 190, 80, 23);

        answer5c.setText("B:<");
        question5.add(answer5c);
        answer5c.setBounds(150, 220, 80, 23);

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        question5.add(jButton9);
        jButton9.setBounds(130, 370, 140, 40);

        ordHome7.setText("Home");
        ordHome7.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome7ActionPerformed(evt);
            }
        });
        question5.add(ordHome7);
        ordHome7.setBounds(150, 420, 110, 40);

        backBtn9.setText("Back");
        backBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn9ActionPerformed(evt);
            }
        });
        question5.add(backBtn9);
        backBtn9.setBounds(20, 420, 110, 40);

        background11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question5.add(background11);
        background11.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question5);
        question5.setBounds(0, 0, 400, 480);

        question6.setLayout(null);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Which of the following two is GREATER? 4/10 0.49");
        question6.add(jTextArea9);
        jTextArea9.setBounds(30, 90, 350, 40);

        ordHead8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead8.setForeground(new java.awt.Color(255, 255, 255));
        ordHead8.setText("Higher Level");
        question6.add(ordHead8);
        ordHead8.setBounds(110, 40, 200, 20);

        calc9.setText("Calculator");
        calc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc9ActionPerformed(evt);
            }
        });
        question6.add(calc9);
        calc9.setBounds(280, 420, 110, 40);

        answer66w.setText("C:They are equal.");
        answer66w.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer66wActionPerformed(evt);
            }
        });
        question6.add(answer66w);
        answer66w.setBounds(140, 290, 120, 23);

        answer6c.setText("A:0.49");
        answer6c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer6cActionPerformed(evt);
            }
        });
        question6.add(answer6c);
        answer6c.setBounds(160, 200, 70, 23);

        answer6w.setText("B: 4/10");
        question6.add(answer6w);
        answer6w.setBounds(160, 240, 70, 23);

        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        question6.add(jButton10);
        jButton10.setBounds(120, 360, 140, 40);

        ordHome8.setText("Home");
        ordHome8.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHome8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHome8ActionPerformed(evt);
            }
        });
        question6.add(ordHome8);
        ordHome8.setBounds(150, 420, 110, 40);

        backBtn10.setText("Back");
        backBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn10ActionPerformed(evt);
            }
        });
        question6.add(backBtn10);
        backBtn10.setBounds(20, 420, 110, 40);

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        question6.add(background12);
        background12.setBounds(0, 0, 400, 480);

        HighlvlStats.add(question6);
        question6.setBounds(0, 0, 400, 480);

        getContentPane().add(HighlvlStats);
        HighlvlStats.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void highBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highBtn1ActionPerformed
        NumbersPnl.setVisible(false);
        HighlvlStats.setVisible(true);
        question4.setVisible(true);
        OrdinarylvlStats.setVisible(false);
        
    }//GEN-LAST:event_highBtn1ActionPerformed

    private void ordBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordBtn1ActionPerformed
        NumbersPnl.setVisible(false);
        OrdinarylvlStats.setVisible(true);
        question1.setVisible(true);
        question2.setVisible(false);
        question3.setVisible(false);
        HighlvlStats.setVisible(true);
        

    }//GEN-LAST:event_ordBtn1ActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        new Calculator().setVisible(true);
    }//GEN-LAST:event_calcActionPerformed

    private void ordHomeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMainActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMainActionPerformed

    private void calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc1ActionPerformed

    private void ordHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        OrdinarylvlStats.setVisible(false);
        NumbersPnl.setVisible(true);
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void DevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtnActionPerformed
        this.setVisible(false);
        new QuestionGUI().setVisible(true);

    }//GEN-LAST:event_DevBtnActionPerformed

    private void answer1wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1wActionPerformed

    private void answer2wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer2wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer2wActionPerformed

    private void calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc2ActionPerformed

    private void answerw2wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerw2wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerw2wActionPerformed

    private void answer1w1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer1w1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer1w1ActionPerformed

    private void ordHome1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome1ActionPerformed

    private void backBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn4ActionPerformed

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc4ActionPerformed

    private void answer22wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer22wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer22wActionPerformed

    private void answer11wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer11wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer11wActionPerformed

    private void ordHome2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome2ActionPerformed

    private void backBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                               
       boolean answer = false;
        if(answer1w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer2w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(true);
            question3.setVisible(false);
        }
        else {
            question2.setVisible(true); }
        
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                                       
       boolean answer = false;
        if(answerw2w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer1w1.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(false);
            question3.setVisible(true);
        }
        else {
            question2.setVisible(true);
        }
    
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                                         
       boolean answer = false;
        if(answer11w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer22w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question1.setVisible(false);
            question2.setVisible(false);
            question3.setVisible(true);
            NumbersPnl.setVisible(true);
        }
        else {
            question3.setVisible(true);
        }
    
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void calc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc3ActionPerformed

    private void answer4cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4cActionPerformed

    private void answer4wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer4wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer4wActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO boolean answer=false;
        boolean answer = false;
       
        if(answer4w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer44w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(true);
            question6.setVisible(false);
        }
        else {
            question5.setVisible(true); 
        }
        
    // TODO add your handling code here:
                                   
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ordHome6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome6ActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc8ActionPerformed

    private void answer55wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer55wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer55wActionPerformed

    private void answer5wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer5wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer5wActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //  boolean answer = false;
        boolean answer = false;
        
        if(answer5w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer55w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(false);
            question6.setVisible(true);
        }
        else {
            question6.setVisible(true); 
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void ordHome7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome7ActionPerformed

    private void backBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn9ActionPerformed

    private void calc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_calc9ActionPerformed

    private void answer66wActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer66wActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer66wActionPerformed

    private void answer6cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer6cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer6cActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       
        boolean answer = false ;
        
        if(answer6w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");
        }
        else if (answer66w.isSelected()){
            answer = false;
            JOptionPane.showMessageDialog(null, "sorry that is an incorrect answer, please try again.");            
        }
        else{
            answer = true;
            JOptionPane.showMessageDialog(null, "that is the correct answer ");
        }
        if(answer == true){
            question4.setVisible(false);
            question5.setVisible(false);
            question6.setVisible(true);
            NumbersPnl.setVisible(true);
        }
        else {
            question6.setVisible(true); 
        }
                                
    }//GEN-LAST:event_jButton10ActionPerformed

    private void ordHome8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHome8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ordHome8ActionPerformed

    private void backBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtn10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumberLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumberLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumberLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumberLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumberLC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DevBtn;
    private javax.swing.JPanel HighlvlStats;
    private javax.swing.JPanel NumbersPnl;
    private javax.swing.JPanel OrdinarylvlStats;
    private javax.swing.JRadioButton answer11w;
    private javax.swing.JRadioButton answer1w;
    private javax.swing.JRadioButton answer1w1;
    private javax.swing.JRadioButton answer22w;
    private javax.swing.JRadioButton answer2w;
    private javax.swing.JRadioButton answer33c;
    private javax.swing.JRadioButton answer3c;
    private javax.swing.JRadioButton answer3c1;
    private javax.swing.JRadioButton answer44w;
    private javax.swing.JRadioButton answer4c;
    private javax.swing.JRadioButton answer4w;
    private javax.swing.JRadioButton answer55w;
    private javax.swing.JRadioButton answer5c;
    private javax.swing.JRadioButton answer5w;
    private javax.swing.JRadioButton answer66w;
    private javax.swing.JRadioButton answer6c;
    private javax.swing.JRadioButton answer6w;
    private javax.swing.JRadioButton answerw2w;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn10;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn4;
    private javax.swing.JButton backBtn5;
    private javax.swing.JButton backBtn9;
    private javax.swing.JLabel background10;
    private javax.swing.JLabel background11;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JButton calc;
    private javax.swing.JButton calc1;
    private javax.swing.JButton calc2;
    private javax.swing.JButton calc3;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc8;
    private javax.swing.JButton calc9;
    private javax.swing.JLabel headLbl1;
    private javax.swing.JLabel headLbl3;
    private javax.swing.JButton highBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JButton ordBtn1;
    private javax.swing.JLabel ordHead;
    private javax.swing.JLabel ordHead2;
    private javax.swing.JLabel ordHead3;
    private javax.swing.JLabel ordHead6;
    private javax.swing.JLabel ordHead7;
    private javax.swing.JLabel ordHead8;
    private javax.swing.JButton ordHome;
    private javax.swing.JButton ordHome1;
    private javax.swing.JButton ordHome2;
    private javax.swing.JButton ordHome6;
    private javax.swing.JButton ordHome7;
    private javax.swing.JButton ordHome8;
    private javax.swing.JButton ordHomeMain;
    private javax.swing.JPanel question1;
    private javax.swing.JPanel question2;
    private javax.swing.JPanel question3;
    private javax.swing.JPanel question4;
    private javax.swing.JPanel question5;
    private javax.swing.JPanel question6;
    // End of variables declaration//GEN-END:variables
}
