/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package projectgui;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;




public class QuestionGUI extends javax.swing.JFrame {
    private ArrayList <Question> aList;
    private String name, type;
    private double weighting;
    private int count;
   
    
    
    
    
    /**
     * Creates new form AssessmentGUI
     */
    public QuestionGUI() {
        initComponents();
       aList = new ArrayList <>();
       name = new String();
       type = new String();
       weighting = 0.0;
       count = 0; 
       mainPanel.setVisible(true);
       passwordPanel.setVisible(false);
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        displayBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        markTf = new javax.swing.JTextField();
        answerTf = new javax.swing.JTextField();
        questionTf = new javax.swing.JTextField();
        markLbl = new javax.swing.JLabel();
        answerLbl = new javax.swing.JLabel();
        questionLbl = new javax.swing.JLabel();
        titleLbl = new javax.swing.JLabel();
        ordHomeMain = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        passwordPanel = new javax.swing.JPanel();
        pass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        mainPanel.setLayout(null);

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteBtn.setText("Delete Question");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        mainPanel.add(deleteBtn);
        deleteBtn.setBounds(210, 320, 160, 27);

        searchBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        mainPanel.add(searchBtn);
        searchBtn.setBounds(30, 320, 140, 27);

        displayBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        displayBtn.setText("Display All");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });
        mainPanel.add(displayBtn);
        displayBtn.setBounds(240, 270, 110, 27);

        addBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBtn.setText("Add Question");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        mainPanel.add(addBtn);
        addBtn.setBounds(20, 270, 150, 27);
        mainPanel.add(markTf);
        markTf.setBounds(152, 195, 207, 19);
        mainPanel.add(answerTf);
        answerTf.setBounds(152, 140, 207, 19);
        mainPanel.add(questionTf);
        questionTf.setBounds(152, 87, 207, 19);

        markLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        markLbl.setForeground(new java.awt.Color(238, 238, 238));
        markLbl.setText("Mark");
        mainPanel.add(markLbl);
        markLbl.setBounds(40, 190, 80, 30);

        answerLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        answerLbl.setForeground(new java.awt.Color(238, 238, 238));
        answerLbl.setText("Answer");
        mainPanel.add(answerLbl);
        answerLbl.setBounds(40, 140, 80, 30);

        questionLbl.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        questionLbl.setForeground(new java.awt.Color(238, 238, 238));
        questionLbl.setText("Question");
        mainPanel.add(questionLbl);
        questionLbl.setBounds(27, 89, 100, 20);

        titleLbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLbl.setForeground(new java.awt.Color(238, 238, 238));
        titleLbl.setText("Question Application");
        mainPanel.add(titleLbl);
        titleLbl.setBounds(70, 20, 310, 50);

        ordHomeMain.setText("Home");
        ordHomeMain.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMainActionPerformed(evt);
            }
        });
        mainPanel.add(ordHomeMain);
        ordHomeMain.setBounds(130, 410, 110, 40);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton1);
        jButton1.setBounds(20, 370, 130, 25);

        jButton2.setText("View Saved");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        mainPanel.add(jButton2);
        jButton2.setBounds(210, 370, 150, 25);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(400, 500));
        jLabel1.setMinimumSize(new java.awt.Dimension(400, 500));
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 500));
        mainPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 470);

        passwordPanel.setLayout(null);

        pass.setMaximumSize(new java.awt.Dimension(100, 20));
        pass.setMinimumSize(new java.awt.Dimension(100, 20));
        pass.setPreferredSize(new java.awt.Dimension(100, 20));
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        passwordPanel.add(pass);
        pass.setBounds(200, 210, 100, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Password");
        passwordPanel.add(jLabel3);
        jLabel3.setBounds(80, 210, 80, 22);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        passwordPanel.add(jLabel2);
        jLabel2.setBounds(-3, 5, 400, 460);

        mainPanel.add(passwordPanel);
        passwordPanel.setBounds(0, 0, 400, 470);

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 400, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //get text from textfields
        name = questionTf.getText();
        type = answerTf.getText();
        weighting = Double.parseDouble(markTf.getText());
        
        Question a = new Question();
        a.setName(name);
        a.setType(type);
        a.setWeighting(weighting);
        
        //add object to arraylist
        aList.add(a);
        
        //increment counter
        count++;
    }//GEN-LAST:event_addBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        for(int i = 0; i < aList.size();i++){
            JOptionPane.showMessageDialog(null, "Name: "+aList.get(i).getName()+"\n Type: "+aList.get(i).getType()+"\n Weighting: "+aList.get(i).getWeighting());
        }
    }//GEN-LAST:event_displayBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String searchType = JOptionPane.showInputDialog(null,"Please enter the type you wish to search for");
        
        for(Question x:aList){
            if(searchType.equalsIgnoreCase(x.getType())){
                JOptionPane.showMessageDialog(null, "Name: "+x.getName()+"\n Type: "+x.getType()+"\n Weighting: "+x.getWeighting());
            }
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        if(questionTf.getText().equals("")||answerTf.getText().equals("")||markTf.getText().equals("")){
            JOptionPane.showMessageDialog(null,"You must enter name, type and weighting to delete");
        }
        else if(count ==0){
            JOptionPane.showMessageDialog(null,"Sorry, there are no items to delete at this time");
        }
        else{
            name = questionTf.getText();
            type = answerTf.getText();
            weighting = Double.parseDouble(markTf.getText());
            
            for(int i = 0; i < aList.size();i++){
                if(aList.get(i).getName().equals(name)&&aList.get(i).getType().equals(type)&&aList.get(i).getWeighting()==weighting){
                    aList.remove(i);
                    count = count - 1;
                    JOptionPane.showMessageDialog(null,"Deleted item at index "+i);
                    break;
                }
                if(i==count-1){
                    JOptionPane.showMessageDialog(null,"Sorry, that item could not be found");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void ordHomeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMainActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMainActionPerformed

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        String password="happy";
        
        if(password.equals(pass.getText())){
            passwordPanel.setVisible(false);
            mainPanel.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(null, "incorrect password, please try again");
        }
    }//GEN-LAST:event_passActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        File outFile;
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        try{
            outFile = new File("output.data");
            fStream = new FileOutputStream(outFile);
            oStream = new ObjectOutputStream(fStream);
            
            oStream.writeObject(aList);
            
            JOptionPane.showMessageDialog(null,"File written successfully");
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        File inFile;
        FileInputStream fStream;
        ObjectInputStream oStream;
        
        try{
            inFile = new File("output.data");
            fStream = new FileInputStream(inFile);
            oStream = new ObjectInputStream(fStream);
            
            /*Assessment x;
            x = (Assessment)oStream.readObject();*/
            ArrayList <Question> xList;
            xList = (ArrayList<Question>)oStream.readObject();
            for(Question x:xList){
            JOptionPane.showMessageDialog(null, "Question: "+x.getName()+"Answer: "+x.getType()+"Mark: "+x.getWeighting());
            }
            
            oStream.close();
        }
        catch(IOException e){
            System.out.println(e);
        }
        catch(ClassNotFoundException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel answerLbl;
    private javax.swing.JTextField answerTf;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton displayBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel markLbl;
    private javax.swing.JTextField markTf;
    private javax.swing.JButton ordHomeMain;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPanel passwordPanel;
    private javax.swing.JLabel questionLbl;
    private javax.swing.JTextField questionTf;
    private javax.swing.JButton searchBtn;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
