/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectgui;

import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author x14472008
 */
public class StatsAndProbLC extends javax.swing.JFrame {
    private int score;

    /**
     * Creates new form statsAndFun
     */
    public StatsAndProbLC() {
        initComponents();
        HighlvlStats.setVisible(false);
        OrdinarylvlStats.setVisible(false);
        score = 0;
        ButtonGroup bg1 = new ButtonGroup();
        ButtonGroup bg2 = new ButtonGroup();
        ButtonGroup bg3 = new ButtonGroup();
        ButtonGroup bg4 = new ButtonGroup();
        ButtonGroup bg5 = new ButtonGroup();
        ButtonGroup bg6 = new ButtonGroup();
        
        bg1.add(answer1w);
        bg1.add(answer2w);
        bg1.add(answer3c);
        bg2.add(answer1w1);
        bg2.add(answer2w1);
        bg2.add(answer3c1);
        bg3.add(answer1w2);
        bg3.add(answer2w2);
        bg3.add(answer3c2);
        bg4.add(answer1w3);
        bg4.add(answer2w3);
        bg4.add(answer3c3);
        bg5.add(answer1w4);
        bg5.add(answer2w4);
        bg5.add(answer3c4);
        bg6.add(answer1w5);
        bg6.add(answer2w5);
        bg6.add(answer3c5);
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        StatsPnlLC = new javax.swing.JPanel();
        headLbl1 = new javax.swing.JLabel();
        headLbl3 = new javax.swing.JLabel();
        backBtn1 = new javax.swing.JButton();
        highBtn1 = new javax.swing.JButton();
        ordBtn1 = new javax.swing.JButton();
        calc = new javax.swing.JButton();
        ordHomeMain = new javax.swing.JButton();
        DevBtn = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();
        OrdinarylvlStats = new javax.swing.JPanel();
        Question1 = new javax.swing.JPanel();
        subQ1 = new javax.swing.JButton();
        ordHead = new javax.swing.JLabel();
        answer3c = new javax.swing.JRadioButton();
        answer2w = new javax.swing.JRadioButton();
        answer1w = new javax.swing.JRadioButton();
        backQ1 = new javax.swing.JButton();
        home1 = new javax.swing.JButton();
        calc1 = new javax.swing.JButton();
        jTextArea1 = new javax.swing.JTextArea();
        background2 = new javax.swing.JLabel();
        Question2 = new javax.swing.JPanel();
        ordHead1 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        calc2 = new javax.swing.JButton();
        home2 = new javax.swing.JButton();
        backQ2 = new javax.swing.JButton();
        answer1w1 = new javax.swing.JRadioButton();
        answer2w1 = new javax.swing.JRadioButton();
        answer3c1 = new javax.swing.JRadioButton();
        subQ2 = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();
        Question3 = new javax.swing.JPanel();
        ordHead2 = new javax.swing.JLabel();
        jTextArea4 = new javax.swing.JTextArea();
        calc4 = new javax.swing.JButton();
        home3 = new javax.swing.JButton();
        backQ3 = new javax.swing.JButton();
        answer1w2 = new javax.swing.JRadioButton();
        answer2w2 = new javax.swing.JRadioButton();
        answer3c2 = new javax.swing.JRadioButton();
        subQ3 = new javax.swing.JButton();
        background5 = new javax.swing.JLabel();
        HighlvlStats = new javax.swing.JPanel();
        Question4 = new javax.swing.JPanel();
        ordHead3 = new javax.swing.JLabel();
        jTextArea5 = new javax.swing.JTextArea();
        calc5 = new javax.swing.JButton();
        home4 = new javax.swing.JButton();
        backQ4 = new javax.swing.JButton();
        answer1w3 = new javax.swing.JRadioButton();
        answer2w3 = new javax.swing.JRadioButton();
        answer3c3 = new javax.swing.JRadioButton();
        subQ4 = new javax.swing.JButton();
        background6 = new javax.swing.JLabel();
        Question7 = new javax.swing.JPanel();
        subQ7 = new javax.swing.JButton();
        answer3c6 = new javax.swing.JRadioButton();
        answer2w6 = new javax.swing.JRadioButton();
        answer1w6 = new javax.swing.JRadioButton();
        backQ7 = new javax.swing.JButton();
        home7 = new javax.swing.JButton();
        calc8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ordHead6 = new javax.swing.JLabel();
        background9 = new javax.swing.JLabel();
        Question5 = new javax.swing.JPanel();
        ordHead4 = new javax.swing.JLabel();
        calc6 = new javax.swing.JButton();
        home5 = new javax.swing.JButton();
        backQ5 = new javax.swing.JButton();
        answer1w4 = new javax.swing.JRadioButton();
        answer2w4 = new javax.swing.JRadioButton();
        answer3c4 = new javax.swing.JRadioButton();
        subQ5 = new javax.swing.JButton();
        jTextArea2 = new javax.swing.JTextArea();
        background7 = new javax.swing.JLabel();
        Question6 = new javax.swing.JPanel();
        subQ6 = new javax.swing.JButton();
        answer3c5 = new javax.swing.JRadioButton();
        answer2w5 = new javax.swing.JRadioButton();
        answer1w5 = new javax.swing.JRadioButton();
        backQ6 = new javax.swing.JButton();
        home6 = new javax.swing.JButton();
        calc7 = new javax.swing.JButton();
        ordHead5 = new javax.swing.JLabel();
        jTextArea6 = new javax.swing.JTextArea();
        background8 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(200, 100));
        setMaximumSize(new java.awt.Dimension(400, 480));
        setMinimumSize(new java.awt.Dimension(400, 480));
        setPreferredSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(null);

        StatsPnlLC.setLayout(null);

        headLbl1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        headLbl1.setForeground(new java.awt.Color(240, 240, 240));
        headLbl1.setText("Statistics and Probability");
        StatsPnlLC.add(headLbl1);
        headLbl1.setBounds(50, 10, 310, 50);

        headLbl3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headLbl3.setForeground(new java.awt.Color(255, 255, 255));
        headLbl3.setText("Leaving Cert");
        StatsPnlLC.add(headLbl3);
        headLbl3.setBounds(170, 80, 80, 20);

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });
        StatsPnlLC.add(backBtn1);
        backBtn1.setBounds(20, 420, 110, 40);

        highBtn1.setText("Higher Level");
        highBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highBtn1ActionPerformed(evt);
            }
        });
        StatsPnlLC.add(highBtn1);
        highBtn1.setBounds(120, 130, 160, 70);

        ordBtn1.setText("Ordinary Level");
        ordBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordBtn1ActionPerformed(evt);
            }
        });
        StatsPnlLC.add(ordBtn1);
        ordBtn1.setBounds(120, 240, 160, 70);

        calc.setText("Calculator");
        calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcActionPerformed(evt);
            }
        });
        StatsPnlLC.add(calc);
        calc.setBounds(280, 420, 110, 40);

        ordHomeMain.setText("Home");
        ordHomeMain.setPreferredSize(new java.awt.Dimension(110, 40));
        ordHomeMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordHomeMainActionPerformed(evt);
            }
        });
        StatsPnlLC.add(ordHomeMain);
        ordHomeMain.setBounds(150, 420, 110, 40);

        DevBtn.setText("Developer");
        DevBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevBtnActionPerformed(evt);
            }
        });
        StatsPnlLC.add(DevBtn);
        DevBtn.setBounds(150, 370, 110, 25);

        background3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        StatsPnlLC.add(background3);
        background3.setBounds(0, 0, 400, 480);

        getContentPane().add(StatsPnlLC);
        StatsPnlLC.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.setLayout(null);

        Question1.setPreferredSize(new java.awt.Dimension(400, 480));
        Question1.setLayout(null);

        subQ1.setText("Submit");
        subQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ1ActionPerformed(evt);
            }
        });
        Question1.add(subQ1);
        subQ1.setBounds(150, 360, 78, 25);

        ordHead.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead.setForeground(new java.awt.Color(255, 255, 255));
        ordHead.setText("Question 1");
        Question1.add(ordHead);
        ordHead.setBounds(130, 40, 200, 20);

        answer3c.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer3c.setForeground(new java.awt.Color(238, 238, 238));
        answer3c.setText("3/5");
        Question1.add(answer3c);
        answer3c.setBounds(150, 310, 90, 25);

        answer2w.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer2w.setForeground(new java.awt.Color(238, 238, 238));
        answer2w.setText("3/4");
        Question1.add(answer2w);
        answer2w.setBounds(150, 270, 90, 25);

        answer1w.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer1w.setForeground(new java.awt.Color(238, 238, 238));
        answer1w.setText("2/5");
        Question1.add(answer1w);
        answer1w.setBounds(150, 230, 90, 25);

        backQ1.setText("Back");
        backQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ1ActionPerformed(evt);
            }
        });
        Question1.add(backQ1);
        backQ1.setBounds(20, 420, 110, 40);

        home1.setText("Home");
        home1.setPreferredSize(new java.awt.Dimension(110, 40));
        home1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home1ActionPerformed(evt);
            }
        });
        Question1.add(home1);
        home1.setBounds(150, 420, 110, 40);

        calc1.setText("Calculator");
        calc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc1ActionPerformed(evt);
            }
        });
        Question1.add(calc1);
        calc1.setBounds(280, 420, 110, 40);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Geneva", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("You have 4 coins. Three of the coins are normal, \nbut one of them is heads on both sides. You pick a\n coin at random without looking. The coin you pick\n has heads on one side. What are the odds that if\n you flip the coin over, the other side will be tails?");
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        Question1.add(jTextArea1);
        jTextArea1.setBounds(30, 90, 350, 120);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question1.add(background2);
        background2.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(Question1);
        Question1.setBounds(0, 0, 400, 480);

        Question2.setPreferredSize(new java.awt.Dimension(400, 480));
        Question2.setLayout(null);

        ordHead1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead1.setForeground(new java.awt.Color(255, 255, 255));
        ordHead1.setText("Question 2");
        Question2.add(ordHead1);
        ordHead1.setBounds(130, 80, 200, 20);

        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Geneva", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("If you roll three normal 6-sided dice, what\n are the odds that the dice rolls add up to \n16?");
        jTextArea3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea3PropertyChange(evt);
            }
        });
        Question2.add(jTextArea3);
        jTextArea3.setBounds(60, 140, 290, 60);

        calc2.setText("Calculator");
        calc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc2ActionPerformed(evt);
            }
        });
        Question2.add(calc2);
        calc2.setBounds(280, 420, 110, 40);

        home2.setText("Home");
        home2.setPreferredSize(new java.awt.Dimension(110, 40));
        home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home2ActionPerformed(evt);
            }
        });
        Question2.add(home2);
        home2.setBounds(150, 420, 110, 40);

        backQ2.setText("Back");
        backQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ2ActionPerformed(evt);
            }
        });
        Question2.add(backQ2);
        backQ2.setBounds(20, 420, 110, 40);

        answer1w1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer1w1.setForeground(new java.awt.Color(238, 238, 238));
        answer1w1.setText("1/6");
        Question2.add(answer1w1);
        answer1w1.setBounds(150, 230, 90, 25);

        answer2w1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer2w1.setForeground(new java.awt.Color(238, 238, 238));
        answer2w1.setText("2/36");
        Question2.add(answer2w1);
        answer2w1.setBounds(150, 310, 90, 25);

        answer3c1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer3c1.setForeground(new java.awt.Color(238, 238, 238));
        answer3c1.setText("1/36");
        answer3c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer3c1ActionPerformed(evt);
            }
        });
        Question2.add(answer3c1);
        answer3c1.setBounds(150, 270, 90, 25);

        subQ2.setText("Submit");
        subQ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ2ActionPerformed(evt);
            }
        });
        Question2.add(subQ2);
        subQ2.setBounds(150, 360, 78, 25);

        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question2.add(background4);
        background4.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(Question2);
        Question2.setBounds(0, 0, 400, 480);

        Question3.setLayout(null);

        ordHead2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead2.setForeground(new java.awt.Color(255, 255, 255));
        ordHead2.setText("Question 3");
        Question3.add(ordHead2);
        ordHead2.setBounds(130, 40, 200, 20);

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Geneva", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText(" If you randomly flip 5 normal coins, then what is\n the probability that you roll 3 tails and 2 heads?");
        jTextArea4.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea4PropertyChange(evt);
            }
        });
        Question3.add(jTextArea4);
        jTextArea4.setBounds(30, 90, 350, 40);

        calc4.setText("Calculator");
        calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc4ActionPerformed(evt);
            }
        });
        Question3.add(calc4);
        calc4.setBounds(280, 420, 110, 40);

        home3.setText("Home");
        home3.setPreferredSize(new java.awt.Dimension(110, 40));
        home3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home3ActionPerformed(evt);
            }
        });
        Question3.add(home3);
        home3.setBounds(150, 420, 110, 40);

        backQ3.setText("Back");
        backQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ3ActionPerformed(evt);
            }
        });
        Question3.add(backQ3);
        backQ3.setBounds(20, 420, 110, 40);

        answer1w2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer1w2.setForeground(new java.awt.Color(238, 238, 238));
        answer1w2.setText("4/18");
        Question3.add(answer1w2);
        answer1w2.setBounds(150, 230, 100, 25);

        answer2w2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer2w2.setForeground(new java.awt.Color(238, 238, 238));
        answer2w2.setText("5/20");
        Question3.add(answer2w2);
        answer2w2.setBounds(150, 270, 90, 25);

        answer3c2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        answer3c2.setForeground(new java.awt.Color(238, 238, 238));
        answer3c2.setText("5/16");
        Question3.add(answer3c2);
        answer3c2.setBounds(150, 310, 90, 25);

        subQ3.setText("Submit");
        subQ3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ3ActionPerformed(evt);
            }
        });
        Question3.add(subQ3);
        subQ3.setBounds(150, 360, 78, 25);

        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question3.add(background5);
        background5.setBounds(0, 0, 400, 480);

        OrdinarylvlStats.add(Question3);
        Question3.setBounds(0, 0, 400, 480);

        getContentPane().add(OrdinarylvlStats);
        OrdinarylvlStats.setBounds(0, 0, 400, 480);

        HighlvlStats.setLayout(null);

        Question4.setLayout(null);

        ordHead3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead3.setForeground(new java.awt.Color(255, 255, 255));
        ordHead3.setText("Question 1");
        Question4.add(ordHead3);
        ordHead3.setBounds(120, 40, 200, 20);

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Geneva", 1, 14)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("If you randomly guessed on 5 questions with 4\n answer choices each, then what is the probability \nyou got exactly two correct?");
        jTextArea5.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea5PropertyChange(evt);
            }
        });
        Question4.add(jTextArea5);
        jTextArea5.setBounds(30, 90, 350, 60);

        calc5.setText("Calculator");
        calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc5ActionPerformed(evt);
            }
        });
        Question4.add(calc5);
        calc5.setBounds(280, 420, 110, 40);

        home4.setText("Home");
        home4.setPreferredSize(new java.awt.Dimension(110, 40));
        home4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home4ActionPerformed(evt);
            }
        });
        Question4.add(home4);
        home4.setBounds(150, 420, 110, 40);

        backQ4.setText("Back");
        backQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ4ActionPerformed(evt);
            }
        });
        Question4.add(backQ4);
        backQ4.setBounds(20, 420, 110, 40);

        answer1w3.setBackground(new java.awt.Color(0, 0, 0));
        answer1w3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer1w3.setForeground(new java.awt.Color(238, 238, 238));
        answer1w3.setText("4/5");
        Question4.add(answer1w3);
        answer1w3.setBounds(150, 200, 120, 30);

        answer2w3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer2w3.setForeground(new java.awt.Color(238, 238, 238));
        answer2w3.setText("100/500");
        Question4.add(answer2w3);
        answer2w3.setBounds(150, 250, 120, 30);

        answer3c3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer3c3.setForeground(new java.awt.Color(238, 238, 238));
        answer3c3.setText("135/512");
        Question4.add(answer3c3);
        answer3c3.setBounds(150, 300, 120, 30);

        subQ4.setText("Submit");
        subQ4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ4ActionPerformed(evt);
            }
        });
        Question4.add(subQ4);
        subQ4.setBounds(150, 360, 78, 25);

        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question4.add(background6);
        background6.setBounds(0, 0, 400, 480);

        Question7.setLayout(null);

        subQ7.setText("Submit");
        subQ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ7ActionPerformed(evt);
            }
        });
        Question7.add(subQ7);
        subQ7.setBounds(160, 380, 78, 25);

        answer3c6.setText("25%");
        Question7.add(answer3c6);
        answer3c6.setBounds(160, 350, 90, 23);

        answer2w6.setText("30%");
        Question7.add(answer2w6);
        answer2w6.setBounds(280, 350, 90, 23);

        answer1w6.setText("50%");
        Question7.add(answer1w6);
        answer1w6.setBounds(40, 350, 90, 23);

        backQ7.setText("Back");
        backQ7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ7ActionPerformed(evt);
            }
        });
        Question7.add(backQ7);
        backQ7.setBounds(20, 420, 110, 40);

        home7.setText("Home");
        home7.setPreferredSize(new java.awt.Dimension(110, 40));
        home7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home7ActionPerformed(evt);
            }
        });
        Question7.add(home7);
        home7.setBounds(150, 420, 110, 40);

        calc8.setText("Calculator");
        calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc8ActionPerformed(evt);
            }
        });
        Question7.add(calc8);
        calc8.setBounds(280, 420, 110, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/dylankilkenny/Desktop/Screen Shot 2015-04-09 at 16.40.56.png")); // NOI18N
        Question7.add(jLabel3);
        jLabel3.setBounds(60, 60, 310, 280);

        ordHead6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead6.setForeground(new java.awt.Color(255, 255, 255));
        ordHead6.setText("Question 3");
        Question7.add(ordHead6);
        ordHead6.setBounds(110, 20, 200, 20);

        background9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question7.add(background9);
        background9.setBounds(0, 0, 400, 480);

        Question4.add(Question7);
        Question7.setBounds(0, 0, 400, 480);

        HighlvlStats.add(Question4);
        Question4.setBounds(0, 0, 400, 480);

        Question5.setLayout(null);

        ordHead4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead4.setForeground(new java.awt.Color(255, 255, 255));
        ordHead4.setText("Question 2");
        Question5.add(ordHead4);
        ordHead4.setBounds(140, 0, 200, 20);

        calc6.setText("Calculator");
        calc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc6ActionPerformed(evt);
            }
        });
        Question5.add(calc6);
        calc6.setBounds(280, 420, 110, 40);

        home5.setText("Home");
        home5.setPreferredSize(new java.awt.Dimension(110, 40));
        home5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home5ActionPerformed(evt);
            }
        });
        Question5.add(home5);
        home5.setBounds(150, 420, 110, 40);

        backQ5.setText("Back");
        backQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ5ActionPerformed(evt);
            }
        });
        Question5.add(backQ5);
        backQ5.setBounds(20, 420, 110, 40);

        answer1w4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer1w4.setForeground(new java.awt.Color(238, 238, 238));
        answer1w4.setText("2/12");
        Question5.add(answer1w4);
        answer1w4.setBounds(150, 250, 90, 30);

        answer2w4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer2w4.setForeground(new java.awt.Color(238, 238, 238));
        answer2w4.setText("3/9");
        Question5.add(answer2w4);
        answer2w4.setBounds(150, 300, 90, 30);

        answer3c4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer3c4.setForeground(new java.awt.Color(238, 238, 238));
        answer3c4.setText("2/9");
        Question5.add(answer3c4);
        answer3c4.setBounds(150, 200, 90, 30);

        subQ5.setText("Submit");
        subQ5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ5ActionPerformed(evt);
            }
        });
        Question5.add(subQ5);
        subQ5.setBounds(160, 380, 78, 25);

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Let's say conceiving a girl is twice as likely to \nhappen as conceiving a boy. If you have 3 children \nbased on those odds, what would be the probability\n that you have two boys and a girl?");
        Question5.add(jTextArea2);
        jTextArea2.setBounds(20, 90, 360, 80);

        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question5.add(background7);
        background7.setBounds(0, 0, 400, 480);

        HighlvlStats.add(Question5);
        Question5.setBounds(0, 0, 400, 480);

        Question6.setLayout(null);

        subQ6.setText("Submit");
        subQ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subQ6ActionPerformed(evt);
            }
        });
        Question6.add(subQ6);
        subQ6.setBounds(160, 380, 78, 25);

        answer3c5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer3c5.setForeground(new java.awt.Color(238, 238, 238));
        answer3c5.setText("67/256");
        Question6.add(answer3c5);
        answer3c5.setBounds(150, 240, 110, 30);

        answer2w5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer2w5.setForeground(new java.awt.Color(238, 238, 238));
        answer2w5.setText("87 /326");
        Question6.add(answer2w5);
        answer2w5.setBounds(150, 330, 110, 30);

        answer1w5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        answer1w5.setForeground(new java.awt.Color(238, 238, 238));
        answer1w5.setText("90/300");
        Question6.add(answer1w5);
        answer1w5.setBounds(150, 290, 110, 30);

        backQ6.setText("Back");
        backQ6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQ6ActionPerformed(evt);
            }
        });
        Question6.add(backQ6);
        backQ6.setBounds(20, 420, 110, 40);

        home6.setText("Home");
        home6.setPreferredSize(new java.awt.Dimension(110, 40));
        home6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                home6ActionPerformed(evt);
            }
        });
        Question6.add(home6);
        home6.setBounds(150, 420, 110, 40);

        calc7.setText("Calculator");
        calc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calc7ActionPerformed(evt);
            }
        });
        Question6.add(calc7);
        calc7.setBounds(280, 420, 110, 40);

        ordHead5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        ordHead5.setForeground(new java.awt.Color(255, 255, 255));
        ordHead5.setText("Question 3");
        Question6.add(ordHead5);
        ordHead5.setBounds(110, 20, 200, 20);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText(" A toy factory generates cubes with a random color \n(red or blue) on each side. You buy 7 of the cubes\n and all your cubes have a different number of blue\n squares. You select one of your cubes at random \nand happen to pull up a cube showing only one \nside, which is red. What is the probability that at \nleast two other squares are also red?");
        Question6.add(jTextArea6);
        jTextArea6.setBounds(30, 90, 352, 120);

        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectgui/images/Maths.jpg"))); // NOI18N
        Question6.add(background8);
        background8.setBounds(0, 0, 400, 480);

        HighlvlStats.add(Question6);
        Question6.setBounds(0, 0, 400, 480);

        getContentPane().add(HighlvlStats);
        HighlvlStats.setBounds(0, 0, 400, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void highBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highBtn1ActionPerformed
        StatsPnlLC.setVisible(false);
        HighlvlStats.setVisible(true);
    }//GEN-LAST:event_highBtn1ActionPerformed

    private void ordBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordBtn1ActionPerformed
        StatsPnlLC.setVisible(false);
        OrdinarylvlStats.setVisible(true);
    }//GEN-LAST:event_ordBtn1ActionPerformed

    private void calcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calcActionPerformed

    private void ordHomeMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordHomeMainActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_ordHomeMainActionPerformed

    private void DevBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevBtnActionPerformed
        this.setVisible(false);
        new QuestionGUI().setVisible(true);
    }//GEN-LAST:event_DevBtnActionPerformed

    private void subQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ1ActionPerformed
        if(answer3c.isSelected()){
            score++;
            Question1.setVisible(false);
        Question2.setVisible(true);
        Question3.setVisible(false);
            }
       else if ( answer1w.isSelected() || answer2w.isSelected()){
         Question1.setVisible(false);
        Question2.setVisible(true);
        Question3.setVisible(false);
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question1.setVisible(true);
       }
    }//GEN-LAST:event_subQ1ActionPerformed

    private void backQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ1ActionPerformed
        OrdinarylvlStats.setVisible(false);
        StatsPnlLC.setVisible(true);
    }//GEN-LAST:event_backQ1ActionPerformed

    private void home1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home1ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home1ActionPerformed

    private void calc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc1ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc1ActionPerformed

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextArea1PropertyChange

    private void jTextArea3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea3PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea3PropertyChange

    private void calc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc2ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc2ActionPerformed

    private void home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home2ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home2ActionPerformed

    private void backQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ2ActionPerformed
        Question2.setVisible(false);
        Question1.setVisible(true);

    }//GEN-LAST:event_backQ2ActionPerformed

    private void subQ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ2ActionPerformed
        if(answer3c1.isSelected()){
            score++;
            Question1.setVisible(false);
        Question2.setVisible(false);
        Question3.setVisible(true);
            }
       else if ( answer1w1.isSelected() || answer2w1.isSelected()){
         Question1.setVisible(false);
        Question2.setVisible(false);
        Question3.setVisible(true);
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question2.setVisible(true);
       }
    }//GEN-LAST:event_subQ2ActionPerformed

    private void jTextArea4PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea4PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea4PropertyChange

    private void calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc4ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc4ActionPerformed

    private void home3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home3ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home3ActionPerformed

    private void backQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ3ActionPerformed
        Question3.setVisible(false);
        Question2.setVisible(true);
    }//GEN-LAST:event_backQ3ActionPerformed

    private void subQ3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ3ActionPerformed
        if(answer3c2.isSelected()){
            score++;
            Question1.setVisible(false);
        Question2.setVisible(false);
        Question3.setVisible(false);
        StatsPnlLC.setVisible(true);
        JOptionPane.showMessageDialog(null, "congrats, you got "+score+"/3 correct :).");
            }
       else if ( answer1w2.isSelected() || answer2w2.isSelected()){
         Question1.setVisible(false);
        Question2.setVisible(false);
        Question3.setVisible(false);
        StatsPnlLC.setVisible(true);
        JOptionPane.showMessageDialog(null, "congrats, you got "+score+"/3 correct :).");
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question3.setVisible(true);
       }
    }//GEN-LAST:event_subQ3ActionPerformed

    private void jTextArea5PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea5PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextArea5PropertyChange

    private void calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc5ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc5ActionPerformed

    private void home4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home4ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home4ActionPerformed

    private void backQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ4ActionPerformed
        HighlvlStats.setVisible(false);
        StatsPnlLC.setVisible(true);
    }//GEN-LAST:event_backQ4ActionPerformed

    private void subQ4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ4ActionPerformed
        if(answer3c3.isSelected()){
            score++;
        Question4.setVisible(false);
        Question5.setVisible(true);
        Question6.setVisible(false);
            }
       else if ( answer1w3.isSelected() || answer2w3.isSelected()){
        Question4.setVisible(false);
        Question5.setVisible(true);
        Question6.setVisible(false);
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question4.setVisible(true);
       }
    }//GEN-LAST:event_subQ4ActionPerformed

    private void calc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc6ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc6ActionPerformed

    private void home5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home5ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home5ActionPerformed

    private void backQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ5ActionPerformed
        Question5.setVisible(false);
        Question4.setVisible(true);
    }//GEN-LAST:event_backQ5ActionPerformed

    private void subQ5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ5ActionPerformed
         if(answer3c4.isSelected()){
            score++;
            Question4.setVisible(false);
        Question5.setVisible(false);
        Question6.setVisible(true);
            }
       else if ( answer1w4.isSelected() || answer2w4.isSelected()){
         Question4.setVisible(false);
        Question5.setVisible(false);
        Question6.setVisible(true);
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question5.setVisible(true);
       }
    }//GEN-LAST:event_subQ5ActionPerformed

    private void subQ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ6ActionPerformed
            if(answer3c5.isSelected()){
            score++;
            Question4.setVisible(false);
        Question5.setVisible(false);
        Question6.setVisible(false);
        StatsPnlLC.setVisible(true);
        JOptionPane.showMessageDialog(null, "congrats, you got "+score+"/3 correct :).");
            }
       else if ( answer1w5.isSelected() || answer2w5.isSelected()){
         Question4.setVisible(false);
        Question5.setVisible(false);
        Question6.setVisible(false);
        StatsPnlLC.setVisible(true);
        JOptionPane.showMessageDialog(null, "congrats, you got "+score+"/3 correct :).");
       }
       
       else{
           JOptionPane.showMessageDialog(null, "Please select an answer!!");
           Question6.setVisible(true);
       }
    }//GEN-LAST:event_subQ6ActionPerformed

    private void backQ6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ6ActionPerformed
        Question6.setVisible(false);
        Question5.setVisible(true);
    }//GEN-LAST:event_backQ6ActionPerformed

    private void home6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home6ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home6ActionPerformed

    private void calc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc7ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc7ActionPerformed

    private void subQ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subQ7ActionPerformed
        if(answer3c5.isSelected()){
            score++;
        }

        Question4.setVisible(false);
        Question5.setVisible(false);
        Question6.setVisible(false);
        StatsPnlLC.setVisible(true);
        JOptionPane.showMessageDialog(null, "congrats, you got "+score+"/3 correct :).");
    }//GEN-LAST:event_subQ7ActionPerformed

    private void backQ7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQ7ActionPerformed
        Question6.setVisible(false);
        Question5.setVisible(true);
    }//GEN-LAST:event_backQ7ActionPerformed

    private void home7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_home7ActionPerformed
        this.setVisible(false);
        new MainMenu().setVisible(true);
    }//GEN-LAST:event_home7ActionPerformed

    private void calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calc8ActionPerformed
        new CalcGui().setVisible(true);
    }//GEN-LAST:event_calc8ActionPerformed

    private void answer3c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer3c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer3c1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatsAndProbLC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatsAndProbLC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DevBtn;
    private javax.swing.JPanel HighlvlStats;
    private javax.swing.JPanel OrdinarylvlStats;
    private javax.swing.JPanel Question1;
    private javax.swing.JPanel Question2;
    private javax.swing.JPanel Question3;
    private javax.swing.JPanel Question4;
    private javax.swing.JPanel Question5;
    private javax.swing.JPanel Question6;
    private javax.swing.JPanel Question7;
    private javax.swing.JPanel StatsPnlLC;
    private javax.swing.JRadioButton answer1w;
    private javax.swing.JRadioButton answer1w1;
    private javax.swing.JRadioButton answer1w2;
    private javax.swing.JRadioButton answer1w3;
    private javax.swing.JRadioButton answer1w4;
    private javax.swing.JRadioButton answer1w5;
    private javax.swing.JRadioButton answer1w6;
    private javax.swing.JRadioButton answer2w;
    private javax.swing.JRadioButton answer2w1;
    private javax.swing.JRadioButton answer2w2;
    private javax.swing.JRadioButton answer2w3;
    private javax.swing.JRadioButton answer2w4;
    private javax.swing.JRadioButton answer2w5;
    private javax.swing.JRadioButton answer2w6;
    private javax.swing.JRadioButton answer3c;
    private javax.swing.JRadioButton answer3c1;
    private javax.swing.JRadioButton answer3c2;
    private javax.swing.JRadioButton answer3c3;
    private javax.swing.JRadioButton answer3c4;
    private javax.swing.JRadioButton answer3c5;
    private javax.swing.JRadioButton answer3c6;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backQ1;
    private javax.swing.JButton backQ2;
    private javax.swing.JButton backQ3;
    private javax.swing.JButton backQ4;
    private javax.swing.JButton backQ5;
    private javax.swing.JButton backQ6;
    private javax.swing.JButton backQ7;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel background3;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JLabel background8;
    private javax.swing.JLabel background9;
    private javax.swing.JButton calc;
    private javax.swing.JButton calc1;
    private javax.swing.JButton calc2;
    private javax.swing.JButton calc4;
    private javax.swing.JButton calc5;
    private javax.swing.JButton calc6;
    private javax.swing.JButton calc7;
    private javax.swing.JButton calc8;
    private javax.swing.JLabel headLbl1;
    private javax.swing.JLabel headLbl3;
    private javax.swing.JButton highBtn1;
    private javax.swing.JButton home1;
    private javax.swing.JButton home2;
    private javax.swing.JButton home3;
    private javax.swing.JButton home4;
    private javax.swing.JButton home5;
    private javax.swing.JButton home6;
    private javax.swing.JButton home7;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JButton ordBtn1;
    private javax.swing.JLabel ordHead;
    private javax.swing.JLabel ordHead1;
    private javax.swing.JLabel ordHead2;
    private javax.swing.JLabel ordHead3;
    private javax.swing.JLabel ordHead4;
    private javax.swing.JLabel ordHead5;
    private javax.swing.JLabel ordHead6;
    private javax.swing.JButton ordHomeMain;
    private javax.swing.JButton subQ1;
    private javax.swing.JButton subQ2;
    private javax.swing.JButton subQ3;
    private javax.swing.JButton subQ4;
    private javax.swing.JButton subQ5;
    private javax.swing.JButton subQ6;
    private javax.swing.JButton subQ7;
    // End of variables declaration//GEN-END:variables
}
